### ISSUE TITLE
Tesselating Block Model Crash

### ISSUE THREAD

**Issue by Cicopath** [gamma-delta/HexMod#100]
Minecraft: 1.18.2
Forge: 40.1.45
Hex Casting: 0.8.3
Kotlin: 3.3.2
PAUCAL: 0.4.5
Patchouli: 69

Yesterday, I was playing Minecraft with many mods, with no problem. Today, I installed Hex Casting, Kotlin, and PAUCAL. Unfortunately, every time I joined the server, I keep getting a Tesselating Block Model-related crash. I load in to the world just fine for a quick second, then it suddenly crashes when attempting to load a chunk with a certain block in it, I believe? Here are two of the crash reports:

[crash-2022-06-05_14.32.03-client.txt](https://github.com/gamma-delta/HexMod/files/8840542/crash-2022-06-05_14.32.03-client.txt)
[crash-2022-06-05_14.42.28-client.txt](https://github.com/gamma-delta/HexMod/files/8840541/crash-2022-06-05_14.42.28-client.txt)

I believe this does not relate to anything with Patchouli, as I've been using it for a few days. I'm thinking it's something related to the libraries, Kotlin and PAUCAL.

EDIT: ~~Accidentally pressed Enter before even detailing what happened! Currently editing my message, please be patient...~~ There we go, all edited back in!

**Comment by Cicopath** [comment]
Odd. I removed Hex Casting, along with all of its dependencies, excluding Patchouli, and am now using Forge 40.1.46. I deleted all of the configs of such mods as well, but the crash is still occurring. Is this a Forge issue?

**Comment by yrsegal** [comment]
This is not Hex.
