### ISSUE TITLE
[Suggestion] Recosting & Rebalacing Spells (Fractional Costs and Cost Rebalancing)

### ISSUE THREAD

**Issue by KirinDave** [gamma-delta/HexMod#101]
As discussed with Wiresegal awhile ago (and now that I can type) I wanted to formally suggest a broad recosting of many of the spells we currently have. We discussed 3 goals:

-  Make some spells dramatically less expensive once you have acquired a flask.
- Encourage the use of early game ciphers and trinkets rather than simply delaying the use of the mod until a Craft Phial scroll, some Chorus Fruit and a record have been found.
- Make some spells less expensive overall to encourage their use.

WireSegal suggested setting a base cost expected (e.g., for break block it would be 1 dust) and then adding +0.125 to that cost. This is a trivial amount of power for a flask or trinket, but for non-flask casting effectively doubles the cost.

Spells that I propose are currently too expensive and should use a reduction (coupled with the extra overhead) include:

1. *Blink*: It's *very* expensive and unlike Impulse cannot be Thoth-chained. Recommended to reduce cost by half.
2. *Explosion & Fireball*:  Initial cost should be made fractional, reduce amplification cost somewhat. For mining, this spell is tricky to use. For PvE fights, this spell is less effective in most cases than using Impulse, except against the Ender Dragon.
3. *Place Block*: Recommend a trivial cost of 0.125 Dust.
4. *Break Block*: Recommended: 1.125 Dust. 
5. *Overgrow*: Increase cost to 1.125 Dust. As it stands, this spell is so good it and Conjure Light are reasons to start using the mod.
6. *Extinguish Area*: Recommended to reduce cost to 1.2 Amethyst Shards
7. *Recharge Item*: Recommended to reduce cost, but I'm not sure by how much.

I hope I didn't forget anything. I compiled this list by looking over the Discord history for various conversations I and others have had, to try and collect feedback.

**Comment by gamma-delta** [comment]
These all sound good! To be honest I *really* need to sit down and do a playthrough of the game with my mod ... but you sound like you know what you're doing.
