### ISSUE TITLE
Crash when using soulglimmer pigment

### ISSUE THREAD

**Issue by ElNico56** [gamma-delta/HexMod#105]
[crash-2022-06-08_09.29.25-client.txt](https://github.com/gamma-delta/HexMod/files/8861970/crash-2022-06-08_09.29.25-client.txt)

**Comment by gamma-delta** [comment]
1. Do you have PAUCAL installed?
2. What version is it? For Hex Casting 0.8.x you should be on PAUCAL 0.3.4.

**Comment by ElNico56** [comment]
i have paucal 0.4.5

**Comment by gamma-delta** [comment]
Try 0.3.4. 0.4.x versions won't work until we release hexcasting 0.9.

**Comment by gamma-delta** [comment]
Considering this closed for now...
