### ISSUE TITLE
Crash on world load caused by massive nesting of NBT tags in a spell

### ISSUE THREAD

**Issue by amadornes** [gamma-delta/HexMod#106]
I'm not the one running into this issue and haven't played with the mod, so I can't provide full details on how to reproduce it, but @Soaryn should be able to provide additional details if needed.

This crash in question happens during level loading (singleplayer), and is triggered by deserialization of NBT tags deeper than Minecraft can handle in the player's inventory (>512). This triggers vanilla's safe loading screen, preventing the player from accessing the world.

Attached are both the crashlog and a selectively edited level.dat file containing just the affected item.  
The spell in question is the third/fourth in the list (I forget which).  
[level_dat_but_a_zip_so_github_lets_me_upload_it.zip](https://github.com/gamma-delta/HexMod/files/8865694/level_dat_but_a_zip_so_github_lets_me_upload_it.zip)  
[latest_trimmed.log](https://github.com/gamma-delta/HexMod/files/8865699/latest_trimmed.log)

**Comment by gamma-delta** [comment]
Of course Soaryn was the one to break it 🤣
