### ISSUE TITLE
Client Crash with Hex Casting on a server (java.lang.ClassNotFoundException: at.petrak.paucal.api.contrib.Contributors)

### ISSUE THREAD

**Issue by ThugPug43** [gamma-delta/HexMod#107]
The crash apparently happens when casting.
https://pastebin.com/Zwj8xhSk

**Comment by ThugPug43** [comment]
I think it might be the soulglimmer pigment causing the issue

**Comment by gamma-delta** [comment]
What version of PAUCAL are you on? For Hexcasting 0.8.3 you want 0.3.4.

**Comment by gamma-delta** [comment]
Duplicate of #105; go to that issue please.
