### ISSUE TITLE
Can't copy pattern into scroll

### ISSUE THREAD

**Issue by wqferr** [gamma-delta/HexMod#108]
Version 0.8.3

Expected behavior: pattern is copied into scroll as described in the book, under Scrolls.
Actual behavior: player throws item into the ground, saying it can't accept a pattern.

![image](https://user-images.githubusercontent.com/13891260/172881945-2e806f79-76bf-4d6f-a925-48184b74c7d1.png)

As I understand, this should be returning 1 since the book mentions I can inscribe patterns into scrolls. When I try to do it with scribe's gambit, it throws the scroll on the ground and says it can't accept a pattern. I tested the same thing with the focus and it worked, so I'm not sure if I misunderstood how scrolls work or if it's an actual bug. I'll flag it as a bug for now, but sorry if i'm just being dense.

**Comment by gamma-delta** [comment]
Known bug on 0.8.x! It will be fixed in 0.9.

(Don't worry, you are *not* the first person to be puzzled ... this is probably the most common question I've been asked about Hexcasting heehee)

**Comment by gamma-delta** [comment]
Yknow what I'm gonna make a pinned issue.
