### ISSUE TITLE
Can't write a pattern to a scroll on v0.8.3?

### ISSUE THREAD

**Issue by gamma-delta** [gamma-delta/HexMod#109]
This is a known bug! It's fixed in 0.9, which will hopefully be out by Monday, 13th June, 2022.

**Comment by Hooviey** [comment]
Hi, I'm playing on the fabric version of 9.0, and for some reason I'm still unable to write spells to scrolls. In fact, the game actively labels them as being unwritable with the "Auditor's Purification II" spell. 
![2022-06-13_16 46 30](https://user-images.githubusercontent.com/81059556/173445187-a05ceb40-ffbb-452d-a8bb-91a54c89bede.png)

If it helps at all, this was experienced in the Blanketcon 2022 modpack. Sorry for the hassle, and I hope things go smoothly with bugfixing!

**Comment by gamma-delta** [comment]
You should only be writing patterns to scrolls; use Consideration, then draw a pattern, *then* try writing it.

(Also please open a fresh issue in the future instead of commenting on this one!)
