### ISSUE TITLE
Teleporting others is an effective means of item theft

### ISSUE THREAD

**Issue by KirinDave** [gamma-delta/HexMod#110]
It has been noted that teleporting other people is an excellent means of "killing" them and this is to be expected. However, Hexmod's notable change is that teleporting others can also cause them to drop items. Many servers that allow pvp or griefing do so because they have `keepInventory` or a grave mod set up to stop item theft or item griefing.

It's quite easy to make a "shakedown" of another player and with the current rules there really is no way to stop people from stealing/voiding/lava-dunking items this way.

I'd recommend gating this aspect of greater teleport behind a configuration item, or finding some other way to prevent griefing with it, for server owners who are concerned about the problem.

**Comment by LedinecMing** [comment]
Yeah that should be configurable, but with a unique config like "dropItemsOnTeleport"
