### ISSUE TITLE
Noteblock scrying lens overlay doesn't display on Fabric

### ISSUE THREAD

**Issue by gamma-delta** [gamma-delta/HexMod#111]
May also be the case on Forge, haven't checked.

**Comment by yrsegal** [comment]
That isn't the case in the dev environment. I'm not sure if this was patched, or if it's an interaction with another mod causing the issue
![2022-06-11_18 09 48](https://user-images.githubusercontent.com/6596492/173206458-ef5011b8-a093-458f-a1c9-b135e12150a7.png)

**Comment by gamma-delta** [comment]
Yeah I just tried it and I can't seem to reproduce it. I think Phonos might mess with noteblocks?

I'll close it for now but this is something to be looked back on eventually, I just don't feel like binary searching for the culprit rn.
