### ISSUE TITLE
Jeweler Hammer doesn't drops Hex Casting items

### ISSUE THREAD

**Issue by Sofistico** [gamma-delta/HexMod#121]
1. Find a Amethyst cluster
2. With a Jeweler Hammer in hand, try to destroy it
3. Note that the only thing that drops is a single amethyst shard
4. Try the same action with a vanilla pickaxe, note that it works.

The problem seems to be that Jeweler Hammer doesn't have the tag "minecraft:cluster_max_harvestables".

**Comment by gamma-delta** [comment]
Yep, that's a known issue, and it was closed a commit or two ago. (Whoopsy.)
