### ISSUE TITLE
The MAX_SERIALIZATION_TOTAL is orders of magnitude too low

### ISSUE THREAD

**Issue by Dudblockman** [gamma-delta/HexMod#122]
Even a relatively simple replication of a short list 10 times causes MAX_SERIALIZATION_TOTAL to trigger and destroy the entire stack

![image](https://user-images.githubusercontent.com/10262784/173486579-f7e49e20-18c3-447b-958b-0e30bb9ab8fc.png)

![image](https://user-images.githubusercontent.com/10262784/173486593-c6191a2d-ef9e-4748-bf06-0664cd2050e1.png)

![image](https://user-images.githubusercontent.com/10262784/173486711-621bfc99-72c8-4e76-9a0b-2daa55131a03.png)

https://github.com/gamma-delta/HexMod/blob/10c9d074b8d2c5dceaf2467f61cbc1ef8cfdb0e8/Common/src/main/java/at/petrak/hexcasting/api/spell/SpellDatum.kt#L110

**Comment by yrsegal** [comment]
I just checked - this is actually not the issue. The issue is that the serialization depth compounds in a way it really shouldn't.
