### ISSUE TITLE
[Feature Request] Allow Scribe's Purification to Read from Readable Items (focuses, spellbooks, scrolls, abacuses) in item frames.

### ISSUE THREAD

**Issue by KirinDave** [gamma-delta/HexMod#123]
I was discussing a potential feature with Wiresegal that encapsulates a lot of the other feature requests we have regarding a way to make complex physically modeled programs before spell circles, and they asked me to file a formal feature request.

Could we please modify Scribe''s purification to look inside item frames and placed scroll entities for iotas to read to the stack? This is simple in concept and doesn't replace spell circles, but it allows for extremely sophisticated devices to exist. Some examples we immediately thought of included:

1. You could search a room and find all existing frames, ordered by distance, and then execute something like a spell compilation that exists as a physical space. 
2. It would let spell circles have player-swappable variables.
3. It would let you put a bit of automation in a physical space and let casters execute it (e.g., something that kicks off a flying machine, something that breaks all the crops in a field, something that causes a Create contraption door to open). 
4. It would let you create hashmaps of patterns in physical space and have a spell look for custom patterns and then refer to them in physical space.

This does impact the akashic record, but what's nice about the akashic record is that it is more compact, supports true names, and reading has no range limitation. I think this keeps a reasonable balance.

Wiresegal also had a few things to say which I will quote:

> but yeah attaching dataholders to entities would be possible and I think that's actually a very good idea
> because the idea of having rooms that are your compilation schema is sick
> and it doesn't allow for 3-pattern circles of arbitrary pattern size

**Comment by gamma-delta** [comment]
Oh my god that's the best fucking idea I've ever heard
