### ISSUE TITLE
[Request] Config to disable spawning with the book on first join

### ISSUE THREAD

**Issue by NielsPilgaard** [gamma-delta/HexMod#128]
Hi there \o

I'd like to request a config option for not spawning with the Hex Casting book when you join a world for the first time. I find it can be a bit overwhelming if you get a lot of stuff straight off the bat.

I hope you'll consider it :D

**Comment by gamma-delta** [comment]
You can do it with a datapack... enough people have asked for this I should probably just make the datapack for you, so you can stick it in your world folder if you like.

I have it given on world load just because I can't think of a better way to point players towards geodes.

**Comment by NielsPilgaard** [comment]
Alright thanks - Would this do the trick? 😄 
https://github.com/EnigmaticaModpacks/Enigmatica8/commit/4a4130a2ec11bddc53429062a67088b28fa4f7c1

**Comment by gamma-delta** [comment]
Maybe? Datapacks aren't my strong suit. I would do it by replacing the `pools` table with an empty list here: https://github.com/gamma-delta/HexMod/blob/main/Common/src/main/resources/data/hexcasting/loot_tables/grant_patchi_book.json

But whatever works, I guess. Try it out and see.

**Comment by NielsPilgaard** [comment]
It works \o/

This approach should save an onTick listener as I understand it, that's always nice.
