### ISSUE TITLE
How to get colorizer in SpellOperator?

### ISSUE THREAD

**Issue by slava110** [gamma-delta/HexMod#129]
Is it possible to get color of caster's colorizer in `SpellOperator`'s `execute` function in form of `int color`?

**Comment by gamma-delta** [comment]
`IXplatAbstractions.INSTANCE.getColorizer(ctx.caster)` will get you the colorizer itself, then use the `getColor` method (it has a good javadoc)

**Comment by gamma-delta** [comment]
Are you on the discord? You'll probably get quicker feedback there 😅

**Comment by slava110** [comment]
Yep. Should I ask in `#general` or `#help` about development-related stuff?
