### ISSUE TITLE
[Feature Request] Add a way for spell circles to act independently from a player

### ISSUE THREAD

**Issue by foul-fortune-feline** [gamma-delta/HexMod#137]
Might be kind of a big change mechanically, but here are my thoughts on what would actually need to be done
1) Provide an "offhand" to spell circles, ex through a directix with a hopper-fed inventory
2) Add a specific impetus for this use case, for which mind's reflection will fail

Alternatively, allowing item stacks to spoof an offhand slot would enable such functionality through the cleric impetus, but would have more knock-on effects for hex casting in general (fex the use of CADs would broaden significantly)

Notes:
 - cartographer may be a good fit for either the impetus or the directix, as would librarian tho they're already used for akashic libraries

This would allow for the automation of more complex tasks ie through the use of place block, which is currently fairly limited in scope by my understanding

**Comment by gamma-delta** [comment]
We are working on it. One of the planned changes for 1.0 is to abstract the
player out of the casting system.

So sit tight for now...

**Comment by gamma-delta** [comment]
So yeah i guess i'll close this since i did technically address it
