### ISSUE TITLE
Unable to craft sealed focus

### ISSUE THREAD

**Issue by Blockguy24** [gamma-delta/HexMod#139]
![image](https://user-images.githubusercontent.com/21016331/174477124-11abe98b-767f-4265-bbd2-35035be3520d.png)

The content of the focus is `1.0000` but I also tried with a list of patterns to no avail.

Version Information:
- Minecraft 1.18.2
- Java 17
- Forge 40.1.0
- Hex Casting 0.9.0
- Just Enough Items 9.7.0.196
- Kotlin for Forge 3.6.0
- Patchouli 1.18.2-70
- PAUCAL 0.4.7

**Comment by Blockguy24** [comment]
It appears as if https://github.com/gamma-delta/HexMod/commit/1a1302b67e0e63215572a89e35dd5fb6e9eb0aed may have already addressed this issue, feel free to close this if this is the case.

**Comment by gamma-delta** [comment]
![image](https://user-images.githubusercontent.com/29877714/175974958-1ea8f6aa-5fc9-4220-b57e-985879a43148.png)
Well, it was fixed at some point, heh
