### ISSUE TITLE
Notebook loading error

### ISSUE THREAD

**Issue by SandWoodJones** [gamma-delta/HexMod#143]
When using  the 1.18.2 0.9.0 fabric version i get
![image](https://user-images.githubusercontent.com/35671374/175135428-217a8639-9394-418b-b694-89f5a39cf7b4.png)
[log.txt](https://github.com/gamma-delta/HexMod/files/8961280/log.txt)

**Comment by SalWolffs** [comment]
Same here, logs roughly similar, visuals identical.
[log.txt](https://github.com/gamma-delta/HexMod/files/8961357/message.txt)

**Comment by gamma-delta** [comment]
Yep, it's a Patchouli problem. Thanks @LemmaEOF for figuring it out!
