### ISSUE TITLE
We need to rewrite the documentation for consideration and advanced Hermes'

### ISSUE THREAD

**Issue by gamma-delta** [gamma-delta/HexMod#146]
Right now the docs are cramped, outdated, and don't document @KirinDave's lookup table tech, how Considered iotas work very well, or the new evaluation of a single pattern.

(I didn't edit the docs when closing #125 because I figured we needed to rewrite the whole thing and afaik like 3 people in the entire world want that feature haha)

**Comment by KirinDave** [comment]
On this, #151 updates the hermes gambit documentation minimally to reflect the new (unusual) type signature, describes what it means, and mention Charon's Gambit can halt evaluation. I'm happy to keep working on this and push it over the line for 0.9.1 if that's helpful.

For describing the lookup table (and Alwinfy's conditional construct), I would like to propose writing a new chapter in the book entitled "Practical Hexxing" which describes 3 simple programs:

1. A simple raycast block break.
2. A simple use of Thoth to play a note when players are nearby
3. Something simple that needs a conditional? I'm drawing a blank before my coffee.

It'll mean adding a new section, new entries, and several new pictures of programs. 

Is this too much?

**Comment by gamma-delta** [comment]
Ooh that would be great! That second thing might be best for Hexcasting
1.0, but yeah feel free to write it.

**Comment by gamma-delta** [comment]
Closed by #151
