### ISSUE TITLE
[BUG]Hermes will not read a pattern on its own

### ISSUE THREAD

**Issue by 3733WOLF** [gamma-delta/HexMod#157]
Bug as stated 
Steps to recreate: try to read from a scroll, and hermes that pattern and will throw out an error expecting list 

occurs every time you read from a single pattern

**Comment by gamma-delta** [comment]
What version are you playing? Hermes' Gambit evaluating bare patterns was only implemented in 0.9.1.

**Comment by 3733WOLF** [comment]
This was in 0.9.0 indeed, good to know it was fixed already
