### ISSUE TITLE
Exception in mouseDrag when drawing hex (w/ Quilt+other mods)

### ISSUE THREAD

**Issue by autumn-birds** [gamma-delta/HexMod#164]
I've been playing a single-player survival world with an admittedly rather haphazardly thrown together clump of mods on the Quilt launcher, including Hex Casting.  I just discovered (maybe should've done testing earlier, hmmmmm...) that attempting to draw a hex crashes the game.  Specifically

- right clicking with staff worked, the dot grid came up as expected
- I left-clicked and attempted to start to drag out a hex experimentally
- the game froze, saving the world, and then crashed to desktop

The log trace mentions Fabric fiber serialization exception (specifically, `0` being an "invalid serialized value.") I don't know anything much about the internals of Quilt or Fabric to guess, but I half suspect this might be an issue caused by my using Quilt. ...I'm aware that Quilt is still in beta, and asking projects to provide support for a beta modloader when the bug might be in the modloader itself (or the Quilt libraries) is potentially too much to ask. <.<

Anyway, here is all the relevant information I can think of.

**Operating system:** Windows 10
**HexMod:** Hex Casting v0.9.1 (`hexcasting-fabric-1.18.2-0.9.1.jar`)
**Mod loader:** Quilt version `quilt-loader-0.17.1-beta.4-1.18.2` (I tried beta.5 too, same result)
**Launcher:** Vanilla launcher, pointed at a directory managed by `packwiz`

**Log file from crash:** [latest.log](https://github.com/gamma-delta/HexMod/files/9035807/latest.log)
**Crash-report file from crash:** [crash-2022-07-03_17.22.49-client.txt](https://github.com/gamma-delta/HexMod/files/9035808/crash-2022-07-03_17.22.49-client.txt)

**Command line in launcher:** `-Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M` (Only changed memory allocation iirc, I'd imagine it's irrelevant)

Files in the `mods` directory:

```
AdditionalAdditions-4.0.5.jar                        indium-1.0.6+mc1.18.2.jar
Adorn-3.5.0+1.18.2-fabric.jar                        lazydfu-0.1.2.jar
Botania-1.18.2-434-FABRIC.jar                        lithium-fabric-mc1.18.2-0.7.10.jar
Patchouli-1.18.2-71.1-FABRIC.jar                     lovely_snails-1.0.4+1.18.jar
Pehkui-3.3.3+1.14.4-1.19.1.jar                       malum-quilt-b1.0.9.jar
PresenceFootsteps-1.5.1.jar                          matchbox-0.2.4.jar
TaxFreeLevels-1.3.jar                                mininggadgets-1.11.0.jar
Terra-fabric-6.0.0-BETA+a9248435a-shaded-mapped.jar  mousewheelie-1.10.1+mc1.18.2.jar
appleskin-fabric-mc1.18.2-2.4.0.jar                  no-telemetry-1.3.0.jar
architects-palette-fabric-2.2.jar                    owo-lib-0.7.2+1.18.jar
architectury-4.5.75-fabric.jar                       paucal-fabric-1.18.2-0.4.7.jar
bagels_baking-1.18.2-0.5.1.jar                       phonos-0.3+1.18.2.jar
bewitchment-1.18-22.jar                              polaroidcamera-1.2.9.jar
cardinal-components-api-4.1.4.jar                    promenade-2.6.3.jar
charmonium-fabric-1.18.2-4.1.0.jar                   purpeille-2.3.2+fabric-1.18.2.jar
cloth-config-6.2.62-fabric.jar                       qcraft-1.1.0.jar
consistency_plus-0.5.0+1.18.2-fabric.jar             qsl-1.1.0-beta.19_qfapi-1.0.0-beta.22_fapi-0.56.0_mc-1.18.2.jar
continuity-2.0.0+1.18.2.jar                          sodium-fabric-mc1.18.2-0.4.1+build.15.jar
create-mc1.18.2_v0.4.1+637.jar                       spectrum-1.4.2-1.18.2-chaos_and_exploration.jar
dawn-3.3.2.jar                                       starlight-1.0.2+fabric.89b8d9f.jar
dynamic-fps-2.1.0.jar                                structure-tools-1.0.22.jar
emi-0.2.0+1.18.2.jar                                 sync-mc1.18.2-4.1.jar
entityculling-fabric-mc1.18-1.5.1.jar                trinkets-3.3.1.jar
fabric-language-kotlin-1.8.1+kotlin.1.7.0.jar        twigs-fabric-1.1.3+legacy.1.18.2.jar
ferritecore-4.2.1-fabric.jar                         wired-redstone-0.3.2.jar
fusions-grappling-hook-1.1.1.jar                     wraith-waystones-2.5.4.jar
hexcasting-fabric-1.18.2-0.9.1.jar
```

(I also tried updating the updateable mods, but this didn't help either.)

I'm happy to provide further information or do testing if needed.

**Comment by autumn-birds** [comment]
Incidentally I've found that Hex Casting on the Fabric loader does not have this issue. (re: mod setup described in #165) I couldn't *completely* rule out a mod incompatibility, though, as mods are not the same.

**Comment by TheOnlyMann** [comment]
wierd, my setup was in fabric, not quilt

**Comment by gamma-delta** [comment]
Whoops!

To fix it, you can delete the `hexcasting-client.json5` file in the `config` folder. Or, if you have config there you'd like to save, add `"gridSnapThreshold": 0.5` (making sure it's still valid JSON, commas between every key-value pair, no trailing comma).

**Comment by autumn-birds** [comment]
Hmm... Deleting the config file didn't actually effect a fix by itself, and when I looked in on said file, the value `"gridSnapThreshold"` was there, but set to zero. Setting it to 0.5 (presumably any nonzero value, possibly only nonnegative values who knows) fixed the issue for me, though, thank you.

**Comment by ProfanedBane** [comment]
> Whoops!
> 
> To fix it, you can delete the `hexcasting-client.json5` file in the `config` folder. Or, if you have config there you'd like to save, add `"gridSnapThreshold": 0.5` (making sure it's still valid JSON, commas between every key-value pair, no trailing comma).

Hey, a few of my friends have ran into this issue even with the config file setup properly, and with the config files of players that don't have the issue. It's seemingly random and out of a group of 5 people, 2 of them crash when drawing hexes.

To reproduce (on affected machines):

- Minecraft 1.18.2
- Fabric Loader 0.14.10
- Fabric API 0.59.1
- Cardinal 4.2.0
- Fabric Kotlin 1.8.5
- Patchouli 71.1
- Paucal 0.4.7
- Hexcasting 0.9.4

- Spawn a dark oak wand
- Right click
- Try to draw
- Crash

Crashlog: 
[crash-2022-11-07_17.33.59-client(1).txt](https://github.com/gamma-delta/HexMod/files/9956175/crash-2022-11-07_17.33.59-client.1.txt)
