### ISSUE TITLE
Crash when loading into world - Only Hexcraft and dependencies installed

### ISSUE THREAD

**Issue by Gamerbolts** [gamma-delta/HexMod#173]
Hello. I am working on a large modpack and Hexcraft loaded just fine. I was trying to create a resourcepack to prevent the book from spawning on player load and to avoid waiting for my modpack each time to load I decided to just load Hexcraft and it's dependencies. I just hit install on Hexcraft on Curseforge and it installed everything for me. I tried loading a world and it crashed.

Here is the crashlog:
[crash-2022-07-18_10.49.38-client.txt](https://github.com/gamma-delta/HexMod/files/9133435/crash-2022-07-18_10.49.38-client.txt)
[crash-2022-07-18_10.49.35-server.txt](https://github.com/gamma-delta/HexMod/files/9133437/crash-2022-07-18_10.49.35-server.txt)

Mods and versions:
Cardinal Components v4.20
Fabric API 0.57.0
Fabric Language Kotlin v1.7.0
Hexcasting v0.9.1
Patchouli v71.1
PAUCAL v0.4.7

The only thing I can think of for the reasoning it works in my modpack and not alone is another mod in my modpack has a embedded Cardinal Components that is overwriting this one. However I am not good with mods or coding so I have no clue. Any help is appreciated. Thank you.

**Comment by gattsuru** [comment]
In the short term, Cardinal Components 4.1.4 works for most things, _excluding Edify Sapling_.  Cardinal Components 4.2.0 doesn't seem to have any relevant breaking changes, but the current ``Fabric/gradle.properties`` doesn't support it.

**Comment by f-raZ0R** [comment]
Am able to reproduce
[crash-2022-07-30_07.27.59-client.txt](https://github.com/gamma-delta/HexMod/files/9226158/crash-2022-07-30_07.27.59-client.txt)
