### ISSUE TITLE
Teleporting an entity riding another doesn't work properly

### ISSUE THREAD

**Issue by yrsegal** [gamma-delta/HexMod#186]
There are a few possible solutions to this. Some examples

1. Teleporting an entity riding something else dismounts that entity and teleports it
- Pro: Teleporting a player out of a cart would make sense conceptually
- YMMV: Teleporting a minecart teleports the player in it
- Con: Teleporting a Create contraption probably would have strange and unexpected effects
2. Teleporting an entity removes it from the entity stack (breaking it into below/above) and teleports it
- Pro: Teleporting an entity out of a stack makes total sense conceptually - only it goes
- YMMV: Teleporting a minecart doesn't teleport the player
- Con: Create Contraptions probably act weird
3. Teleporting an entity riding something else teleports the entire entity stack
- Pro: Create contraptions work great
- YMMV: Minecart teleporting
- Con: Teleporting a zombie jockey takes the chicken with it
4. Teleporting an entity riding something else mishaps
- YMMV: Current behavior, but formalized.

**Comment by gamma-delta** [comment]
What currently happens re "doesn't work properly"?

**Comment by yrsegal** [comment]
(the same thing happens with /tp, for reference)

**Comment by gamma-delta** [comment]
whoops

I'm inclined to say option 2, but with a tag to activate option 3 for given entity IDs like contraptions.

Hey come to think of it, are Botania spectral-rail-ed minecarts a separate entity? That could be a really cool interaction! If you can get the timing down enough you can teleport the minecart while it's midair hell I'll let you keep your items)

**Comment by yrsegal** [comment]
the spectral rail effect is just a component/capability attached to the minecart - presumably it also flips the nogravity flag

**Comment by gamma-delta** [comment]
I added a tag. Cool bonus feature: pigs/horses/striders can teleport, so if you really want you can get on a pig, greater teleport the pig, and your items will stay on you! If you're willing to do that much BS then I'll it to you
