### ISSUE TITLE
Spells let you break out of adventure mode's constraints

### ISSUE THREAD

**Issue by yrsegal** [gamma-delta/HexMod#188]
Break, place, etc should be limited by the rules of adventure mode if you're in adventure mode.

**Comment by gamma-delta** [comment]
We *might* want a mishap for this cause right now it just silently fails, which is confusing. Altho it is a pretty rare occurrence.

**Comment by yrsegal** [comment]
This solution doesn't allow blocks with the tag that let you place them in adventure mode to be placed by Place Block. Admittedly, an edge case, but...
