### ISSUE TITLE
[0.9.1] Great Spell generation can overlap with Number Literals. Number Literals take priority, causing certain seeds to be missing certain Great Spells.

### ISSUE THREAD

**Issue by FistoDaOrc** [gamma-delta/HexMod#190]
In this case; On a server with some friends, the Make Phial spell generated with the pattern deddwqwqwwaadwweqaaweweedqqqqqdqa. As the beginning of this pattern starts the way it does, instead of making a phial when compiled, it outputs the number -141.0000.

**Comment by object-Object** [comment]
I don't have an ingame repro, but this seems to have regressed in 0.10.x somehow.

0.9: https://github.com/gamma-delta/HexMod/blob/1.18/Common/src/main/java/at/petrak/hexcasting/api/PatternRegistry.kt#L86
0.10: https://github.com/gamma-delta/HexMod/blob/main/Common/src/main/java/at/petrak/hexcasting/api/PatternRegistry.java#L85

**Comment by gamma-delta** [comment]
yep, i think it regressed when porting it to java

**Comment by gamma-delta** [comment]
Fixed at some point
