### ISSUE TITLE
Serialization Hooks needs a bump

### ISSUE THREAD

**Issue by TropheusJ** [gamma-delta/HexMod#195]
So funny story, Hexcasting was the perfect mod to hide the fact that Serialization Hooks literally didn't work in the first version.
Fixing it came with some breaking changes, which means that once Create 0.5 Fabric/Quilt is out (which includes a newer Porting Lib (which includes a newer Serialization Hooks)) the two won't be compatible until Hexcasting updates.

Should literally be a 2 line update for Hexcasting.
- Current version is `0.3.22` and works on 1.18 and 1.19.
- Ingredient's `toNetwork` must start with writing a `ResourceLocation` to the buffer, which needs to be your `IngredientDeserializer`'s ID.

If there's any issues let me know.

**Comment by yrsegal** [comment]
out of curiosity, how did we *hide* something like that lmao

**Comment by TropheusJ** [comment]
unsealed ingredients have basically the same serialization as vanilla ingredients
not entirely sure but I think they were falling back to vanilla ones instead of erroring

**Comment by yrsegal** [comment]
Handled as part of https://github.com/gamma-delta/HexMod/commit/bd833486b6603116466674242ecbdd7d7c31e365
