### ISSUE TITLE
[feature request] colored stroke order guides

### ISSUE THREAD

**Issue by AmberGoop** [gamma-delta/HexMod#198]
when pressing ctrl, known spells display the order of strokes using the brightness of the line.
however, this can be really hard to read correctly for some people, especially with larger spells.
would it be possible to have a colored line, maybe as a config? 
examples:
![grafik](https://user-images.githubusercontent.com/77462121/181801786-de8a6488-f461-40a7-928d-8de9b9265977.png)
![grafik](https://user-images.githubusercontent.com/77462121/181802214-5fce49c3-3e9e-41c4-a066-8a74cd0d6414.png)

**Comment by object-Object** [comment]
Just something to keep in mind: this might be an issue for colourblind people if not implemented well.
Another idea could be to render a number in the middle of each line? Like 1 for the first line to draw, 2 for the second, etc.

**Comment by AmberGoop** [comment]
i had colorblind people in mind, that's why i mentioned it could be a config instead of the default - but numbers also seem good. probably better than colors in the first place, actually, because with numbers there is absolutely no confusion
so yeah, i'd also be up for numbers.. just, anything more readable than what we have because i am one of the people that have a ton of trouble reading the brightness differences

**Comment by SnazzGass** [comment]
I worked on a python script for displaying patterns that helps differentiate lines by spreading the intersections. I think this solution would be more intuitive and also friendly to colorblind.

blocky:
![artifact_blocky](https://user-images.githubusercontent.com/45057060/184070235-d8ee72c9-5299-4735-b7cb-1760a3b13e36.png)

smooth:
![artifact_smooth](https://user-images.githubusercontent.com/45057060/184070252-b5042307-7cb4-4545-846a-e9b21ad1097f.png)

I also experimented with ways to indicate the length of straight lines.
blocky with notches:
![13_blocky](https://user-images.githubusercontent.com/45057060/184070331-691470f5-7062-42be-b7ea-8baa32fd2518.png)

smooth with dots:
![13_smooth](https://user-images.githubusercontent.com/45057060/184070349-7cb2384e-236d-458e-8886-7b5d3db43ccd.png)

**Comment by NalathniDragon** [comment]
I love the stroke separation approach SnazzGass has (and feel that should be how scrolls are rendered), and would like to propose the [turbo](https://ai.googleblog.com/2019/08/turbo-improved-rainbow-colormap-for.html) color map for colored stroke paths.

**Comment by gamma-delta** [comment]
This has been on the backburner for a while ... my favorite is SnazzGass's, and I think I want it to be the default one full stop.

I'll get to work...

**Comment by gamma-delta** [comment]
@SnazzGass could you link your code? or put it on Github or something?

**Comment by object-Object** [comment]
I think we can close this - 0.10 (iirc) added the fancy corner cutting pattern rendering.
