### ISSUE TITLE
Ignite doesn't work on things that expect interactions with flint and steel

### ISSUE THREAD

**Issue by yrsegal** [gamma-delta/HexMod#199]
I figure that makes sense to add. If the fire charge fails, try flint and steel

also, do we fire forge/fabric events for use there?

**Comment by gamma-delta** [comment]
Probably should iff the event is for "lighting things on fire" and not "using a flint & steel"

**Comment by yrsegal** [comment]
I mean for "using flint and steel"

the idea is things like blaze burners and Immersive Weathering cleaning up mossy blocks
