### ISSUE TITLE
Experiencing a crash when logging into world.

### ISSUE THREAD

**Issue by WisdomNaps** [gamma-delta/HexMod#204]
This is only apparent when I use Cardinal Components version 4.2.0 (It'll either crash immediately or freeze while loading).

**Comment by gattsuru** [comment]
For now, Cardinal Components 4.1.4 will work.  There's fix in PR <https://github.com/gamma-delta/HexMod/pull/183> if you want to be kept updated for when it merges in, but I'm hoping for 0.9.2.
