### ISSUE TITLE
Hex casting spells are able to break unbreakable waystones

### ISSUE THREAD

**Issue by kuba26038** [gamma-delta/HexMod#207]
first of all, i have no clue how this mod works, but apparently someone on my server who does figured out how to break "unbreakable" waystones that scatter the world.
basically, the waystones mod has a config option that allows you to make all naturally generated waystones unbreakable. unfortunately, this doesn't work the best it can- they are still able to be broken with hexes. i don't have a video of that, but here are the steps you need to make to recreate this: 

1- install both the waystones mod and hexcasting
2- enable the naturally generated waystones are unbreakable config option in the waystones config
3-  find a naturally generated waystone (i suggest using the https://www.curseforge.com/minecraft/texture-packs/towers-of-the-wild-reworked-datapack to do that easily)
4- attempt breaking them using a hex

**Comment by kuba26038** [comment]
here's an example of the same problem happening with create drills https://www.youtube.com/watch?v=yYgqfXyR0Yc

**Comment by cylian914** [comment]
so when you spell the break spell it will break the waystone ? maybe ask the dev of waystone to make it unbreakable like bedrock

**Comment by gamma-delta** [comment]
Yeah, this sounds like a bug with Waystones instead of Hexcasting. Go ask them first; if there's some reason they can't do that reopen this and I'll fix it on here
