### ISSUE TITLE
Flay Mind doesn't work

### ISSUE THREAD

**Issue by Vixemy** [gamma-delta/HexMod#208]
It seems that my Flay Mind is bugged. I tried:
- Casting it myself
- Casting it after Scribe's Reflection from the ancient scroll
- I have all Hex notebook entries so I am "Enlightened" 
- Any other great spell works no matter if cast by myself or Scribe's Reflection out of the scroll
I am using "hexcasting-forge-1.18.2-0.9.1.jar"
There is no error connected to entity or vector when I try to cast. The only thing is "That pattern isn't associated with any action"

**Comment by yrsegal** [comment]
Are you sure you're casting the correct Flay Mind? they're different in each world. try giving yourself a new scroll if you can use /hexcasting:patterns?

**Comment by yrsegal** [comment]
A screenshot of the ancient scroll with command/ctrl held would also help

**Comment by gamma-delta** [comment]
Wire, they're casting it direct from the scroll, so this is most likely an us problem

**Comment by yrsegal** [comment]
Maybe, but I can't really tell without seeing the scroll. There might be something wrong with the pattern somehow? Or the scroll itself might have been generated incorrectly somehow, like a version change or something (hence the idea of using /hexcasting:patterns)

**Comment by yrsegal** [comment]
As is, since I can't reproduce this issue, I can't really do anything about it without more information

**Comment by JonathanMStreeter** [comment]
[This is Nice Media Monger] 
I am a fellow programmer.
I walked the person through debugging this. I had them cast it, I had them post the pattern of what the scroll was, the pattern from the ancient scroll, and they matched. Tried to overwrite the ancient scroll and it did not so the scroll was valid. 
Tried 2 zeniths and they both worked, both hand drawn and scroll work. 
They were using the latest version of Hex. The results were always the same, this is not a real pattern. The pattern is written in the bots channel.
I suggested that they make anther world with the same seed, unknown results of that experiment.

**Comment by yrsegal** [comment]
Could you share that seed? That’ll help with debugging

**Comment by Vixemy** [comment]
I can't get my hands on the seed at this given moment but:
- I tested it on single player world
> Random seed
> Creative
> Spawned Flay Mind scroll
It worked properly
- I found another Flay Mind scroll in multi player server
![image](https://user-images.githubusercontent.com/63077131/182654637-6704528b-02bf-4d95-b2df-168c573774ad.png)
> Pattern South_east awqwqwqwqqwqawqqqeqaqeewedqwe is working
> Both scrolls found in the same world

**Comment by yrsegal** [comment]
so, it seems to have been what I suspected - somehow, a scroll was generated incorrectly. I'm... not sure *how...*

**Comment by Vixemy** [comment]
If that will anyhow help I still can provide with world seed later

**Comment by JonathanMStreeter** [comment]
Vixemy you said there were some world gen shenanigans correct? It might be helpful to expand on that.

**Comment by Vixemy** [comment]
So basically before I joined the server there were some "shenanigans" with the world generation. From what I've been told world was generated with TerraForged Mod for the 1.18.2 version of MC for like 30k blocks in every direction. Then it got removed and just default world gen has left. If that info matters both scrolls were found within TerraForged generated part of the world.

**Comment by yrsegal** [comment]
That almost certainly is the issue. Terraforged might have generated the loot before players opened the chests?
