### ISSUE TITLE
Crash with using Oak Staff

### ISSUE THREAD

**Issue by Papaturts** [gamma-delta/HexMod#209]
Im on the fabric version for 1.18.2
[crash-2022-08-02_23.11.35-client.txt](https://github.com/gamma-delta/HexMod/files/9247920/crash-2022-08-02_23.11.35-client.txt)

When trying to use the staff the game instantly crashes for the client
start with right click then left click then crash

**Comment by gattsuru** [comment]
Check your ``hexcasting-client.json5`` config file.  There should be a line similar to :
```	// When using a staff, the distance from one dot you have to go to snap to the next dot, where 0.5 means 50% of the way.
	"gridSnapThreshold": 0.5```
Make sure that this value is set between 0.5 and 1.0.

**Comment by Papaturts** [comment]
thank you
will give it a try
Much appreciated

**Comment by Papaturts** [comment]
This fixed it, thank you much
Much appreciated!!!
