### ISSUE TITLE
[Bug] On Fabric, inserting amethyst into an impetus with Create always acts like a full stack was inserted

### ISSUE THREAD

**Issue by object-Object** [gamma-delta/HexMod#215]
When inserting amethyst into any impetus with a chute, smart chute, andesite funnel, or brass funnel, each stack of items inserted is treated as if it were a full stack. For example, inserting one amethyst dust increases the dust counter by 64, and one amethyst crystal increases it by 320. This doesn't happen with hoppers.

Also, as far as I can tell, you can insert literally any item other than stone into an impetus using Create. It doesn't add any media, the item just disappears.

Mods:
* Fabric
* Hex 0.9.1 (also tested on Arcane Compendium's custom 0.9.2 build)
* Create 0.5.0c-708

**Comment by yrsegal** [comment]
... oh grand
