### ISSUE TITLE
[BUG] [bleeding-edge-builds] Can't change page in spellbook

### ISSUE THREAD

**Issue by Stevebutnottoomanypeoplehaveit** [gamma-delta/HexMod#217]
Scrolling with a spellbook in the offhand while sneaking, or while in the casting gui, doesn't result in the page of the spellbook changing. When sneak-scrolling the selected item on the hotbar doesn't change, so it's doing something, but failing to change the page.

**Comment by yrsegal** [comment]
appears to be a Forge-only issue

**Comment by yrsegal** [comment]
...
wow ok good going me
