### ISSUE TITLE
Mind Flay and Trading

### ISSUE THREAD

**Issue by thedeerirty** [gamma-delta/HexMod#220]
By the consequences of your mind flay activities being seen, does it mean you don't get to trade at all anymore? I'm not 100% positive it is a problem with your fine mod, but its one of the things I interacted with last before I saw the change. Interacting with villagers has them shake their head at me, as if they don't have a profession and doesn't open the trade GUI.

I can however, trade with Wandering Travelers; but with villagers? Nope. No matter what village, no matter if I got hero of the village, can't be done. Is this something your mod has the potential to bug out on at all?

**Comment by yrsegal** [comment]
That's really strange. I don't know why that would happen - we just call the same method that's called when you murder a villager

**Comment by yrsegal** [comment]
Any update on this?

**Comment by thedeerirty** [comment]
Apologies for not responding sooner; I must have missed the initial reply.

I believe it was ultimately not the cause of hexcasting. Sorry for the trouble, though I appreciate the check-in to be sure.
