### ISSUE TITLE
trinket infusion bug

### ISSUE THREAD

**Issue by leafyleaf447** [gamma-delta/HexMod#221]
whenever i try to infuse a trinket it doesnt pick up the fuel even though i have it selected
the error is the at the bottom
![2022-08-15_17 29 42](https://user-images.githubusercontent.com/111325294/184766542-35bd5ac6-2e54-4763-8cca-35c3aa78e089.png)

**Comment by yrsegal** [comment]
You're trying to use a list of an item entity. Craft Trinket uses a single item. Try using Selection Distillation to extract the entity.
