### ISSUE TITLE
[Spell suggestion] Morph entity

### ISSUE THREAD

**Issue by tynberry** [gamma-delta/HexMod#224]
Morph entity
entity, entity -> entity

Morph entity changes the first entity with a clone of the second entity and returns the new entity. This costs a amount of media that is computed from various factors like health, height so it can support entities from other mods.
This pattern doesn't work if any of the two entities are items or players, as duplicating the former would be easy and you cannot dupe players. Also using items as changed entities would be too easy.

Variations:
There could be a chance of failure, where it kills the original, meaning you would need to save a list of clones if you want to automate this forever.
Whatever the system of determination of media, there could be a media multiplier, but that would need to be datapack compatible for cross-mod.

Why:
Because imo it would be a slightly balanced way to summon X as you would need a farm for the target entities and you would need to contain the cloned entity, which for things like wither is slightly difficult.

**Comment by walksanatora** [comment]
i feel like this would be better suited for a addon
transmutation seems a bit out of the scope of hexcasting (we can put minds into blocks but we cannot turn one block into another)

**Comment by object-Object** [comment]
Going to say this is out of scope - seems really complicated and probably better for an addon to implement.
