### ISSUE TITLE
[Bug] Place Block won't take blocks from the offhand, and won't place anything if there's a block in the offhand

### ISSUE THREAD

**Issue by object-Object** [gamma-delta/HexMod#227]
1. Have a block in your offhand.
2. Cast Place Block with a valid location on the stack.

Or

1. Have a block in your offhand and a different block on your hotbar somewhere.
2. Cast Place Block with a valid location on the stack.

Or

1. Have a block in your offhand and more of the same block in your inventory somewhere, on or off your hotbar.
2. Cast Place Block with a valid location on the stack.

In all of these cases, no block is placed. At least in the first and third cases, I'd expect the block / type of block in the offhand to be placed.

Tested on Forge and Fabric with mod version 0.9.1, as well as Arcane Compendium's 0.9.2-requiem-alpha-g on Fabric.

**Comment by yrsegal** [comment]
is this still the case with the discovery handler changes?

**Comment by object-Object** [comment]
...nope! this is fixed on the latest CI build
