### ISSUE TITLE
Sticky Teleport issues

### ISSUE THREAD

**Issue by yrsegal** [gamma-delta/HexMod#228]
1. Other horse-likes aren't sticky.
2. Also, should slimes be sticky, because that sounds funny?
3. Also, should sticky teleporting apply to the entire stack, or just adjacent entities on the stack?
a. Currently, sticky teleporting doesn't walk up the stack. If no 3. shouldn't apply, should this be fixed?

**Comment by gamma-delta** [comment]
1. Whoops, please fix that. (Are skeleton horses *really* separate entity IDs? God people)
2. You can't mount slimes in vanilla, so no
3. The entire stack
