### ISSUE TITLE
[Bug] Place Block duplicates block NBT data

### ISSUE THREAD

**Issue by object-Object** [gamma-delta/HexMod#229]
https://user-images.githubusercontent.com/37044997/186054678-547a43b0-e64f-47f6-bcc1-760cfbe6a934.mp4

Notice that the *empty* package was placed, but it has the same items as the non-empty package.

petra made me make this issue

**Comment by yrsegal** [comment]
ed2abee735eb25dd0d1a3811d6ae197c28972792 closes this lol
