### ISSUE TITLE
More Complex One-Off Spells

### ISSUE THREAD

**Issue by 12foo** [gamma-delta/HexMod#23]
Hello! This isn't my favourite mod ever just yet, but it's rapidly getting there. I love the concept, and I've always thought stack-based ~~prog~~ casting is an ideal fit for Minecraft. One thing I really like is that a well-crafted trinket has actual in-game value for giving to your friends, because other players can't easily replicate it.

I would like to propose some suggestions around getting more complex spells on trinkets, but they might also work for casting more complex spells without a spellbook. I am also happy to implement any of them that you think are worthwhile. Please do consider them in light of what the mod's intended balance, and if you decide none of these are good or they are OP, that is fine too. So here goes:

1. Reduce the spacing of the hex grid (and make it configurable) so the player can fit more patterns on screen.
2. Give players the ability to load a pattern list from an already crafted trinket (probably a combined load + erase, so the stored spell can be extended and then re-crafted in one step).
3. External Scribe's Gambit: Saves the top of the stack to a data holding item on the ground.
4. Potion of Clarity + Clear Pattern: while potion effect is active, draw Clear to clear the grid (but not the stack). Consumes potion effect.
5. Snapcasting: Consideration stores the next spell pattern not only on the stack, but in the staff itself (persistently). Drawing Snapcast instantly casts this stored pattern. The intent here is that you can cast large patterns like Craft Artifact or Greater Teleport using the (much smaller) Snapcast pattern.

Edit: some further thinking-- 2. could be how Erase normally works, and 3. is probably better as an external Scribe's Reflection (read data from item on ground). I am not sure if it's a good idea to allow both writing and reading externally balance-wise, since the player could just drop a bunch of foci, do zone->dropped items, and then select from that list to have basically infinite (but cumbersome) data storage.

**Comment by gamma-delta** [comment]
1. There's plans for that! My initial thought is that a Scrying Lens and the advancements on the "main progression" path all reduce the dot spacing
2. That's in 0.6 I think (if not it'll go in 0.6.1)
3. Yeah that's a common ask, that will also go in 0.6.1 I guess
4. and 5. Mm those are cool ideas, but I think with 1-3 there will be enough tools. (Snapcasting is a *good* name though, I might keep that in reserve)

**Comment by 12foo** [comment]
That's great to know! Let me know if you want help with any of those. Also, another suggestion that might replace 2.-- how about giving trinkets a data slot? An in-progress spell could be stored in there until it's crafted onto the trinket, and after it's crafted, it could store a piece of data that's otherwise hard to wrangle. Teleport coordinates come to mind-- you either have to always use a focus with a teleport trinket, or draw the numbers into the spell by hand, which will never fit. Having a data slot on the trinket would make that much easier.

**Comment by gamma-delta** [comment]
0.7.0 adds:
- Scrying lens in the offhand makes the grid size smaller
- Scribe's Reflection (which *reads* from an item entity)

So I'm considering this closed
