### ISSUE TITLE
[Suggestion] Add config to disable give book when player first join

### ISSUE THREAD

**Issue by elementsplayer** [gamma-delta/HexMod#233]

**Comment by object-Object** [comment]
As a workaround, you can use this datapack: https://github.com/SamsTheNerd/hexaddons/blob/c331f06705736c5907293fb73bb9afe9331d5e59/datapacks/NoHexModBookOnStart.zip

**Comment by object-Object** [comment]
duplicate of #452 (this is older but there's more discussion there)
