### ISSUE TITLE
[Crash] Game fails to load when using latest version of Hex

### ISSUE THREAD

**Issue by krallendertoten** [gamma-delta/HexMod#234]
Hex version: hexcasting-forge-1.18.2-0.9.2.jar
Forge version: 40.1.73
Launcher: MultiMC
Pastebin link for crash log snippet: https://pastebin.com/ZZuhNQR9

Mod List:
 1.18.2-betteramethyst-1.0.1.jar
 AI-Improvements-1.18.2-0.5.0.jar
 AdLods-1.18.2-6.0.1.1-build.1026.jar
 AttributeFix-Forge-1.18.2-14.0.2.jar
 AutoRegLib-1.7-53.jar
 BetterAdvancements-1.18.1-0.1.2.122.jar
 BetterF3-1.2.5-Forge-1.18.2.jar
 Bookshelf-Forge-1.18.2-13.2.47.jar
 Botania-1.18.2-435.jar
 Clumps-forge-1.18.2-8.0.0+15.jar
 CommonCapabilities-1.18.2-2.8.2.jar
 Controlling-forge-1.18.2-9.0+21.jar
 CosmeticArmorReworked-1.18.2-v2.jar
 CraftTweaker-forge-1.18.2-9.1.185.jar
 CyclopsCore-1.18.2-1.16.0.jar
 DarkModeEverywhere-1.18.1-1.0.2.jar
 DungeonsArise-1.18.2-2.1.50d-beta.jar
 EnchantmentDescriptions-Forge-1.18.2-10.0.4.jar
 Enlightened+End+RE+Release+V1.1.jar
 EpicFight-18.3.3-beta.jar
 EyesInTheDarkness-1.18.2-1.2.7.jar
 FarmersDelight-1.18.2-1.1.2.jar
 FastFurnace-1.18.2-6.0.3.jar
 FastSuite-1.18.2-3.0.2.jar
 FastWorkbench-1.18.2-6.1.0.jar
 FixMySpawnR-forge-1.18.2-1.0.0.jar
 ForgeEndertech-1.18.2-9.0.4.0-build.1016.jar
 FpsReducer2-forge-1.18.2-2.0.jar
 ImmersiveEngineering-1.18.2-8.2.0-151.jar
 IntegratedCrafting-1.18.2-1.0.23.jar
 IntegratedDynamics-1.18.2-1.11.8.jar
 IntegratedREST-1.18.2-1.1.5.jar
 IntegratedTerminals-1.18.2-1.3.0.jar
 IntegratedTunnels-1.18.2-1.8.13.jar
'InventoryHud_[1.18].forge-3.4.4.jar'
 Jade-1.18.2-forge-5.2.3.jar
 JadeAddons-1.18.2-2.4.0.jar
 JustEnoughResources-1.18.2-0.14.1.171.jar
 MmmMmmMmmMmm-1.18.2-1.5.2.jar
 MouseTweaks-forge-mc1.18-2.21.jar
 NaturesCompass-1.18.2-1.9.7-forge.jar
 NekosEnchantedBooks-1.18.2-1.7.0.jar
 NethersDelight-1.18.2-2.2.0.jar
 Paraglider-1.18.2-1.6.0.0.jar
 Patchouli-1.18.2-71.1.jar
 Placebo-1.18.2-6.5.3.jar
 Quark-3.2-358.jar
 QuarkOddities-1.18.jar
 ReAuth-1.18-Forge-4.0.4.jar
 StorageDrawers-1.18.2-10.2.1.jar
 Terralith_v2.2.1a.jar
 ToastControl-1.18.2-6.0.3.jar
 TravelersTitles-1.18.2-Forge-2.1.1.jar
 XaerosWorldMap_1.26.5_Forge_1.18.2.jar
 Xaeros_Minimap_22.13.0_Forge_1.18.2.jar
 YungsApi-1.18.2-Forge-2.0.8.jar
 YungsBetterDungeons-1.18.2-Forge-2.1.0.jar
 YungsBetterMineshafts-1.18.2-Forge-2.2.jar
 YungsBetterStrongholds-1.18.2-Forge-2.1.1.jar
 YungsBetterWitchHuts-1.18.2-Forge-1.0.1.jar
 YungsBridges-1.18.2-Forge-2.1.0.jar
 YungsExtras-1.18.2-Forge-2.1.0.jar
 abnormals_delight-1.18.2-3.0.1.jar
 additionallanterns-1.0.1-mc1.18.jar
 allurement-1.18.2-2.0.0.jar
 appleskin-forge-mc1.18.2-2.4.1.jar
 appliedenergistics2-11.1.5.jar
 architectury-4.9.83-forge.jar
 balm-3.2.0+0.jar
 berry_good-1.18.2-5.0.0.jar
 betterfpsdist-1.18.2-1.5.jar
 blueprint-1.18.2-5.4.3.jar
 boatload-1.18.2-3.0.0.jar
 buzzier_bees-1.18.2-4.0.0.jar
 carryon-1.18.2-1.17.0.8.jar
 cc-tweaked-1.18.2-1.100.9.jar
 chunkloaders-1.2.2-forge-mc1.18.jar
 clienttweaks-forge-1.18.1-7.1.0.jar
 cloth-config-6.2.62-forge.jar
 comforts-forge-1.18.2-5.0.0.4.jar
 configured-1.5.3-1.18.2.jar
 craftingtweaks-forge-1.18.2-14.0.3.jar
 create-1.18.2-0.5.0.d.jar
 curios-forge-1.18.2-5.0.7.1.jar
 elytrabounce-1.18.2-1.0.1.jar
 entityculling-forge-mc1.18-1.5.1.jar
 etched-forge-2.2.0+1.18.2.jar
 extremesoundmuffler-3.28_forge-1.18.2.jar
 feature_nbt_deadlock_be_gone_forge-2.0.0+1.18.2.jar
 ferritecore-4.2.1-forge.jar
 fightnbtintegration-1.18.2-1.0.3.jar
 flywheel-forge-1.18.2-0.6.5.jar
 foodeffects-1.18.2-1.1.3.jar
 forgivingvoid-forge-1.18.1-6.0.1.jar
 geckolib-forge-1.18-3.0.34.jar
 hexcasting-forge-1.18.2-0.9.2.jar
 incubation-1.18.2-2.0.2.jar
 infernal-expansion-1.18.2-2.5.0.jar
 ironchest-1.18.2-13.1.9.jar
 jei-1.18.2-9.7.1.232.jar
 kleeslabs-forge-1.18.2-11.1.1.jar
 kotlinforforge-3.7.1-obf.jar
 krypton-0.1.10-SNAPSHOT.jar
 littlelogistics-mc1.18.2-v1.2.6.jar
 miningmaster-1.18.2-3.0.5.jar
 modnametooltip-1.18.1-1.18.0.jar
 mutil-1.18.2-4.5.0.jar
 neapolitan-1.18.2-3.0.0.jar
 netherportalfix-forge-1.18-9.0.0.jar
 oculus-mc1.18.2-1.2.5a.jar
 paucal-forge-1.18.2-0.4.7.jar
 personality-1.18.2-2.0.0.jar
 pollen-forge-1.4.9+1.18.2.jar
 polymorph-forge-1.18.2-0.44.jar
 radium-0.7.10.jar
 reliquary-1.18.2-2.0.12.1143.jar
 repurposed_structures_forge-5.1.14+1.18.2.jar
 rubidium-0.5.3a.jar
 savage_and_ravage-1.18.2-4.0.0.jar
 secondchanceforge-1.18.2-1.5.0.jar
 selene-1.18.2-1.17.9.jar
 simpleplanes-1.18.2-4.15.0.jar
 sophisticatedbackpacks-1.18.2-3.18.17.680.jar
 sophisticatedcore-1.18.2-0.5.1.98.jar
 sophisticatedstorage-1.18.2-0.5.1.107.jar
 spark-1.9.11-forge.jar
 starlight-1.0.2+forge.546ae87.jar
 supermartijn642configlib-1.1.6-forge-mc1.18.jar
 supermartijn642corelib-1.0.19-forge-mc1.18.jar
 supplementaries-1.18.2-1.4.8.jar
 swingthroughgrass-1.18.2-1.9.0.jar
 tetra-1.18.2-4.9.3.jar
 time-in-a-bottle-2.1.0-mc1.18.1.jar
 trashslot-forge-1.18.1-11.0.2.jar

**Comment by object-Object** [comment]
Minimal modlist:
```
paucal-forge-1.18.2-0.4.7.jar
hexcasting-forge-1.18.2-0.9.2.jar
kotlinforforge-3.7.1-obf.jar
Patchouli-1.18.2-71.1.jar
```

**Comment by EtherialMind** [comment]
From what I can tell this issue is caused by a rubidium conflict. Currently going to the previous Hexcasting version should allow you to keep playing for now. P.S. I am no expert this is just a conclusion I have come through from dealing with rubidium's hacky nature for so long that I recognize its influence in crash logs. If anyone can give further details, I would highly appreciate it.

**Comment by ewsmith** [comment]
I don't have rubidium, and I get the exact same crash.

modlist: [https://pastebin.com/HhnwQANN](https://pastebin.com/HhnwQANN)

**Comment by yrsegal** [comment]
https://github.com/gamma-delta/HexMod/commit/9aa301957134ed59347c04a4ffc253937a515696 fixes this. Release soon.

**Comment by SansCipher** [comment]
New version (including the linked commit) did not fix the crash
