### ISSUE TITLE
[Crash] Hex crashing on startup even on the newest version 

### ISSUE THREAD

**Issue by krallendertoten** [gamma-delta/HexMod#236]
Same issue as in https://github.com/gamma-delta/HexMod/issues/234 but using hex 0.9.3, happens with and without other mods
Hex version: hexcasting-forge-1.18.2-0.9.3.jar
Forge version: 40.1.73

Crash stacktrace: https://pastebin.com/AshhWAme

**Comment by Hahahavana** [comment]
I get the same issue on Hex Casting 0.9.2 and 0.9.3, on both Forge 1.73 and 74. Had to downgrade to Hex Casting v9.1 to fix.

**Comment by Devalut** [comment]
Same issue!

**Comment by oliverrook** [comment]
So this is where this error's been coming from
