### ISSUE TITLE
[Suggestion] Flay Mind support on any LivingEntity

### ISSUE THREAD

**Issue by Vivividly** [gamma-delta/HexMod#237]
This is a bit far fetched but I think it'd be cool if the datapack format for flay mind recipes also supported entities other than Villagers. Notably stuff like guard villagers, or other humanoid entities. These don't need to be implemented in the base mod but having this option would be very cool for modpack developers.

**Comment by luo-zi** [comment]
I think it's a very legitimate need, we're just extracting the minds of humanoids, and obviously there are many humanoids with proper intelligence besides the villagers

**Comment by object-Object** [comment]
Implemented in 0.11!
