### ISSUE TITLE
Casting Greater Teleport via Trinket duplicates Trinket

### ISSUE THREAD

**Issue by 12foo** [gamma-delta/HexMod#24]
See title. This seems to happen because `use()` returns the updated trinket to the hand after GT's cast has already dropped the inventory (including the trinket) on the ground.

https://github.com/gamma-delta/HexMod/blob/343d73aa6a59f5a6672b5eb433ea1c689654728d/src/main/java/at/petrak/hexcasting/common/items/magic/ItemPackagedSpell.java#L89

An obvious fix for this would be excluding the trinket itself from dropping. Happy to submit a PR for this, but I didn't want to just go ahead without confirming. Also, since items will already have to be dropped conditionally, perhaps there's room for a mechanic where the shorter the distance teleported, the fewer items are dropped.

**Comment by gamma-delta** [comment]
Ooh yes I would love that, please do
