### ISSUE TITLE
Somehow set internal pigment to air

### ISSUE THREAD

**Issue by GameGuruGreenGryphon** [gamma-delta/HexMod#241]
### Versions

Minecraft: 1.18.2
Forge: 40.1.74
Hex: Commit [c5c7b30](https://github.com/gamma-delta/HexMod/commit/c5c7b302d2b34d3fa1367bae390c985bc1bf45c0)
Paucal: Commit [e4cddd4](https://github.com/gamma-delta/PAUCAL/commit/e4cddd48f8edb48b25ba7266a3aeb442543908ac)

### What happened
Started my survival world, internal pigment was not set and appeared white.
Updated Hex to commit [c5c7b30](https://github.com/gamma-delta/HexMod/commit/c5c7b302d2b34d3fa1367bae390c985bc1bf45c0), from commit [ee05eb1](https://github.com/gamma-delta/HexMod/commit/ee05eb1a4eb48e81a0aa1866e64bc440938d0329).
Setting my pigment to hexcasting:dye_colorizer_green set the apparent pigment to magenta, unable to be changed further.
Using /data get entity @p ForgeData.hexcasting:colorizer reveals that the id used for the colorizer is minecraft:air, instead of a colorizer item name.
Creating a new world and setting the internal pigment works as intended.

![javaw_VKsJwTGB7t](https://user-images.githubusercontent.com/87587913/188524365-f274947a-b0f9-4cfe-836a-9848106bf09b.png)

**Comment by PhantomEnderium** [comment]
I've had a similar issue within 0.9.1 at least, changing dimensions has a chance to have the sentinel disappear entirely. It's location is still there, just not visually. Resummoning it shows it as solid white.

**Comment by gamma-delta** [comment]
@PhantomEnderium that is happening on the Forge version?

The bug should still be happening in 0.9.4 because I don't think we've touched that code

@yrsegal this smells like a capability serialization issue, could you take a look at it?

**Comment by PhantomEnderium** [comment]
> @PhantomEnderium that is happening on the Forge version?
> 
> The bug should still be happening in 0.9.4 because I don't think we've touched that code
> 
> @yrsegal this smells like a capability serialization issue, could you take a look at it?

forge version yes. haven't really tested it in 0.9.4, but assuming it's the same issue

**Comment by yrsegal** [comment]
if it's on forge, that doesn't make sense for it to be cap serialization, since it's... well, not a cap

i'd say this is probably fixed in 0.9.4 at least for what Phantom is experiencing? Not certain what the original issue is about

**Comment by RedRaspberry** [comment]
Sorry for necro'ing this, but I just downloaded the mod today to try it out on a server with a friend and I can report that the same thing happened to me, verified with the data get command someone posted in here. On 0.9.4 Forge. Can provide modlist and logs if needed

**Comment by object-Object** [comment]
Appears to be fixed, see #270.
