### ISSUE TITLE
Critical dupe with Create

### ISSUE THREAD

**Issue by Vervixer** [gamma-delta/HexMod#243]
Fabric 1.18.2, Hex casting 0.9.2, Create 0.5.0d-731.

If you'll use Blink on Create's contraptions, then some unpredictable behavior may occur, this includes:
- Using on windmills / clockwork bearing / cart assembled carts: actually teleporting windmill's wool / sails / clock's hands / minecart (May be intended) away (Only appear visible after disassembling the contraption except for minecart)
- Using on trains (Critical): create a duplicate of a train that is is disassembled and contains all of the blocks from the train ([result 1](https://cdn.discordapp.com/attachments/874089404103282688/1016793361136488528/unknown.png), [result 2](https://cdn.discordapp.com/attachments/874089404103282688/1016793471509614592/unknown.png))
- When given trinket (Might be other casting items) to deployer it doesn't cost any charge which too may lead to some unintended behavior

Mechanical bearings and pistons seems safe as Blink does not do anything with them

**Comment by yrsegal** [comment]
uuugh, we'll have to add a GTP blacklist, won't we

**Comment by Vervixer** [comment]
Also, I might need another issue but it's somehow connected to Create.
Using integration with Pehkui with well-timed deployers in a [simple TNT remote-controlled cannon](https://cdn.discordapp.com/attachments/920779080532643841/1016768200526016543/unknown-115.png) can lead to some... Let's say [cool](https://cdn.discordapp.com/attachments/920779080532643841/1016769371969957949/unknown-94.png) but unintended effects.

Might be a good idea of white/blacklisting some entities for some spells I think? I mean I do have a whitelisted server so I don't really worry about griefing and stuff, but I do see why it can be a problem on a public one. With even 5-10 of TNT you can literally obliterate anything in minutes. It might be a cool feature for PVP-based servers tho.
