### ISSUE TITLE
[Suggestion] Floating hexes

### ISSUE THREAD

**Issue by ronondex2009** [gamma-delta/HexMod#246]
If it was possible to have a sort of glowing, floating, bobbing-up-and-down hex pattern in the air would be _amazing._ That's about it, even better, if it was possible to take a piece of amethyst dust and write onto it sort of like a scroll, "forming" it into a hex pattern that would be place-able in the world, floating and perhaps creating particles that float down from the hex while it floats.

**Comment by walksanatora** [comment]
Imagine if you could move while casting
And rou could interact with scrolls to immediately execute their hex if they were dusted with amethyst

**Comment by walksanatora** [comment]
Or even a "copy/paste" hex pattern from scroll would be nice

**Comment by gamma-delta** [comment]
For the record, you can read patterns out of scroll entities with ... don't remember the name off the top of my head, Scribe's Purification?

**Comment by walksanatora** [comment]
~~imagine if you could steal all the hexes someone currently has written by getting the position of their hex and using scribes refl~~

**Comment by SamsTheNerd** [comment]
sounds like a great addon idea ! ( might do it in hexgloop )
