### ISSUE TITLE
[Suggestion] Fisherman's Gambit with a negative index buries the top element

### ISSUE THREAD

**Issue by brianide** [gamma-delta/HexMod#247]
Fisherman's Gambit currently mishaps for negative indices. This change would instead make it invert its operation, eg. where `3 fisherman` turns `x y z` into `y z x`, `-3 fisherman` would turn `x y z` into `z x y`.

I'd be happy to put together a PR for this.

**Comment by gamma-delta** [comment]
I'm going to fold this issue into #291 and track progress there, but by all means please, if you fix up the PR i'll pull it
