### ISSUE TITLE
Sentinel doing a funny dance with view bobbing

### ISSUE THREAD

**Issue by GameGuruGreenGryphon** [gamma-delta/HexMod#248]
### Versions
Minecraft: 1.18.2
Fabric: 0.14.9
Hex: Commit [c5c7b30](https://github.com/gamma-delta/HexMod/commit/c5c7b302d2b34d3fa1367bae390c985bc1bf45c0)
Paucal: Commit [e4cddd4](https://github.com/gamma-delta/PAUCAL/commit/e4cddd48f8edb48b25ba7266a3aeb442543908ac)
Cardinal Components API: 4.2.0
Fabric API: 0.58.0+1.18.2
Iris: 1.3.1
Sodium: 0.4.1+build.15
### How to reproduce
With Iris + Sodium installed and view bobbing turned on, summon a sentinel using a staff and walk on the ground while looking at the sentinel, triggering the view bobbing.
_In my opinion_, the sentinel appears to move as if the motion needed to correct how it looks when view bobbing, is multiplied by a constant, making it bounce around as you move. It looks very funny.

**Comment by gamma-delta** [comment]
Oh christ not more fucking matrixstacks, I had to learn quaternions to get it to work even as well as it does, arghh

sigh. Should be doable though; I just need to figure out what transformations the forge version does and copy them
