### ISSUE TITLE
Identity Purification evaluating both 1 and 0 to NULL 

### ISSUE THREAD

**Issue by Petrify** [gamma-delta/HexMod#254]
## Expected Behavior
Identity Purification returns 1 when 1 is passed

## Actual Behavior
Identity Purification returns NULL when 1 is passed.

## Steps to Reproduce the Problem

  1. Draw Numerical Reflection 1 (Or any logical operation that returns 1) 
  3. Draw Identity Purification

## Specifications

  - Mod Verion: 0.9.1
  - Forge Version: 40.1.69
  - Minecraft Version: 1.18.2

**Comment by yrsegal** [comment]
No longer an issue as of 0.9.4
