### ISSUE TITLE
Greater Teleport Failing To Teleport

### ISSUE THREAD

**Issue by Theovore** [gamma-delta/HexMod#256]
So, I made a test artifact to see how coordinates change when you use GTP and get subsumed into energy. Something strange happened. For some reason, GTP worked just fine when you weren't moving but utterly failed when you _were_ moving. Just to make sure, I tried reloading Minecraft to see if the issue persisted. It did. I should note that you do in fact seem to teleport for a frame or two, just that you snap back to where you were previously.
https://user-images.githubusercontent.com/114267685/192070909-e46daa99-12c3-4327-ab1e-b75594853c91.mp4
--------------------------------------------------------------------
Perhaps the patterns will help:
`Mind's Reflection -> Mind's Reflection -> Compass' Purification -> Mind's Reflection -> Alidade's Purification -> Archer's Distillation -> Mind's Reflection -> Compass' Purification -> Subtractive Distillation -> Greater Teleport`
--------------------------------------------------------------------
I was using Fabric 1.18.2, with the following mods (hope you don't mind just the file names):
- appleskin-fabric-mc1.18.2-2.4.1
- architectury-4.9.83-fabric
- betterfpsdist-fabric-1.18-1.8
- Boat-Item-View-Fabric-1.18-0.0.3
- Botania-1.18.2-435-FABRIC
- cardinal-components-api-4.2.0
- cloth-config-6.2.62-fabric
- continuity-2.0.1+1.18.2
- Controlling-fabric-1.18.2-9.0+21
- create-fabric-1.18.2-0.5.0d-731
- dashloader-4.1.3+1.18
- DistantHorizons-1.6.5a-1.18.2
- enchantedshulkers-1.0.4+1.18.2
- entityculling-fabric-mc1.18-1.5.1
- fabric-api-0.58.0+1.18.2
- fabric-language-kotlin-1.7.4+kotlin.1.6.21
- ferritecore-4.2.1-fabric
- Gamma-Utils-1.5.8-mc1.18.2
- hexal-fabric-1.18.2-0.1.3
- hexcasting-fabric-1.18.2-0.9.3
- indium-1.0.7+mc1.18.2
- InventoryHUD-fabric-[1.18]+-3.4.2
- lithium-fabric-mc1.18.2-0.7.10
- logical_zoom-0.0.14
- malilib-fabric-1.18.2-0.12.1
- minihud-fabric-1.18.2-0.22.1
- modmenu-3.2.3
- MouseTweaks-fabric-mc1.18-2.22
- OfflineSkins-1.18.2-v2-fabric
- Patchouli-1.18.2-71.1-FABRIC
- paucal-fabric-1.18.2-0.4.7
- phosphor-fabric-mc1.18.x-0.8.1
- reeses_sodium_options-1.4.7+mc1.18.2-build.58
- RoughlyEnoughItems-8.3.529
- sodium-fabric-mc1.18.2-0.4.1+build.15
- tooltipfix-1.0.4-1.18
- trinkets-3.3.1

**Comment by yrsegal** [comment]
It would help to have a log of this happening, as it might be a "moved too quickly" issue?

**Comment by Theovore** [comment]
What do you mean by log? It didn't seem to crash my game, so are you referencing some log that the game keeps?

**Comment by yrsegal** [comment]
yeah, the game's log. you can find it in the logs folder

**Comment by Theovore** [comment]
Hmm...let me see if I can recreate it again real quick. One moment. (I assume you mean the .log.gz files?)

**Comment by Theovore** [comment]
[2022-10-05-4.log.gz](https://github.com/gamma-delta/HexMod/files/9718089/2022-10-05-4.log.gz)
I believe this file should be the correct one.
I should mention that I was able to replicate this issue with just the following mods:
- cardinal-components-api-4.2.0
- fabric-api-0.58.0+1.18.2
- fabric-language-kotlin-1.7.4+kotlin.1.6.21
- hexcasting-fabric-1.18.2-0.9.3
- Patchouli-1.18.2-71.1-FABRIC
- paucal-fabric-1.18.2-0.4.7

**Comment by yrsegal** [comment]
This was not the correct log. It's a log from when you didn't have an appropriate version of PAUCAL, I think?

**Comment by object-Object** [comment]
Anecdotally, I haven't seen this happen recently, and the issue is pretty old - we can open a new one if necessary.
