### ISSUE TITLE
[Suggestion] Using Comparators on Impetuses

### ISSUE THREAD

**Issue by Theovore** [gamma-delta/HexMod#260]
So, the way comparators work is that they can detect the fill level of things like chests through a solid block. So, while you could keep the energized detection possible by simply making the impetus act like a conditional redstone block, you could also make it so that comparators would be able to detect the fill level of the impetuses, therefore allowing you to create dynamic circle filling systems.

However, one limitation of this would be that the current media limit on impetuses, as far as I am aware, is 200,000 dust. For context, players can carry at most 23,680 dust on them. This would mean that the impetus would need to have a minimum of 12,500 dust to get the comparator to output a redstone signal. So, a way to fix this would be to be able to manipulate the maximum media of an impetus. It could be through some magic item, similar to an abacus, or it could be through a pattern, similar to Flay Mind.

Combined, these two things would be incredibly useful for a large variety of things, including but not limited to amethyst farms, spell circle arrays, and even limiting the amount of media that a spell circle will consume in one activation. Certainly not meaningless changes, in my opinion.

**Comment by yrsegal** [comment]
Huh? That's not what comparators do with impetuses. They only detect energized status, not fill level

**Comment by Theovore** [comment]
That's what I thought initially, but I guess I misinterpreted and/or the people I was talking to misinterpreted what I was saying. Let me edit the suggestion a little, then.

**Comment by SamsTheNerd** [comment]
I believe mediaworks has a pattern for checking how much media is available, not sure how it works for circles though. Otherwise this seems like functionality that could be added some other way without disrupting the energized reading
