### ISSUE TITLE
[suggestion] "Scry" pattern: remote observation

### ISSUE THREAD

**Issue by gedeknepper** [gamma-delta/HexMod#266]
Takes a position vector, a look vector, and a duration double; provides a view of someone standing at the position looking in the look direction for the given duration. Alternatively, takes no look vector, and gives a full-spherical panoramic (i.e., 4 pi steradians) view. Either only visible to the caster (replacing/overlaying normal vision), or a separate, floating screen, in which case it needs another vector argument to place that screen at.

A "sentinel" means "watchman", and this would allow one to actually use them for that purpose.

**Comment by SamsTheNerd** [comment]
seems similar to MediaWork's astral projection
