### ISSUE TITLE
Gemini's Gambit can be used to crash servers & kick clients

### ISSUE THREAD

**Issue by RedRaspberry** [gamma-delta/HexMod#271]
**Affected version**: Playing on latest release 0.9.4
**Forge Version** 40.1.84

**Description**: Running Gemini's gambit with values around ~1Mil, even over an empty list, will kick you from the server from getting too large of a packet.
Running Gemini's gambit with values around ~1Bil is enough to crash my 10gb server from OutOfMemory.

Neither of these values seem sane to reach in normal gameplay, so I assume this is as simple as capping it to a reasonable number.

**Comment by RedRaspberry** [comment]
Sorry, meant to include this in the main post:
**Server crashlog**: https://gist.github.com/RedRaspberry/727073a321b58ae02e73112b2f6b9741

The person who is responsible for the crash couldn't find the details in their client log but sent me a screenshot of the disconnect screen:
![Screenshot 2022-11-04 205206](https://user-images.githubusercontent.com/34117596/200093654-ab86bc04-5cdc-4885-a5c3-b5ab1e7e2915.png)

**Comment by gamma-delta** [comment]
... Huh, the iota limit is supposed to stop that. Good catch!
