### ISSUE TITLE
[Spell Suggestion] Transfer Experience 

### ISSUE THREAD

**Issue by RedRaspberry** [gamma-delta/HexMod#272]
The idea of this spell would be a fairly complex pattern that looks similar to a bottle o' enchanting, that when given a number and an entity removes that much experience from the caster and puts it into the entity at the position (an empty glass bottle). 
Perhaps it could also target other players to allow you to directly transfer xp to your friends.
Obviously it would fail when casted by non players or casted on a nonplayer/bottle.

**Comment by gedeknepper** [comment]
Spell circle spells are associated with a player (in the case of clerical impetus, the bound player), and are able to use Mind's Reflection.

**Comment by RedRaspberry** [comment]
Even better! Automated xp storage remotely

**Comment by SamsTheNerd** [comment]
sounds like a fun addon idea, maybe having it be sculk themed could be neat ?
