### ISSUE TITLE
Hexcasting not generating config.

### ISSUE THREAD

**Issue by qwerty121123** [gamma-delta/HexMod#274]
I have been playing a quilt multiplayer world with friends, with a custom modpack that is pretty much held together with figurative duct tape, staples, and hope. Somehow, the server works fine, but this is a clientside problem for me. Yesterday my client was running fine, but the latest minecraft launcher update (presumably) broke it. It refused to start until I wiped the profile I was using to launch the modpack. Everything except hexcasting works now. I knew I would have to set the `"gridSnapThreshold"` to 0.5. However, to my surprise, there was no config file. I got a friend to send a copy of their config file which I haphazardly pasted into my config folder. Unfortunately, this didn't work, and it is not recognizing the config file. I am unsure how to fix this.

OS: Windows 10
Loader: Quilt, latest ver.
Launcher: Vanilla MC Launcher
Crash Report: [Pastebin](https://pastebin.com/YZXCsGCs)

Log files are not generating for some reason. I wouldn't be able to tell you why.

**Comment by gamma-delta** [comment]
I think this is a Fiber issue but I'm not sure; checking on their issue tracker right now. https://github.com/FabLabsMC/fiber/issues/89

**Comment by qwerty121123** [comment]
Hey, I think it was a problem on my end, Sorry for the bother. I wiped my profile again and it fixed it.
