### ISSUE TITLE
Crash when trying to draw hexes on Fabric/Quilt?

### ISSUE THREAD

**Issue by gamma-delta** [gamma-delta/HexMod#276]
https://github.com/FabLabsMC/fiber/issues/89

The TL;DR is it is *probably* an issue with the version of Java the Curseforge launcher ships. Using Adoptium OpenJDK instead seems to fix it.

**Comment by handicraftsman** [comment]
Does not help for me, still crashing.

**Comment by handicraftsman** [comment]
Using latest openjdk downloaded from adoptium page.

**Comment by kangming06** [comment]
> Does not help for me, still crashing.

The same phenomenon in1.18.2.

**Comment by MiquShiro** [comment]
> Does not help for me, still crashing.
> Using latest openjdk downloaded from adoptium page.
Crashes on 1.18.2 + dont know how to install adoptium properly
