### ISSUE TITLE
[1.0 Preview] Chronicler's Gambit Stack Size Mismatch

### ISSUE THREAD

**Issue by KirinDave** [gamma-delta/HexMod#277]
In attempting to test the #123 support in the current 1.0 preview build, I tried to read from one focus in itemframe and transfer it to another focus in itemframe. While doing so, I discovered `Chronicler's Gambit` incorrectly sizes the stack. 

With a stack depth of 2, it fails and claims: `Chronicler's Gambit expected 2 or more arguments but the stack was only 1 tall.` I've attempted to vary the stack depth, but it's the same result for any stack depth.

Either: 

1. I'm not actually allowed to write to focuses in item frames, in which case this error message is wrong.
2. The stack depth check for the spell operator is wrong.

**Comment by gamma-delta** [comment]
whoops i bet i set argc=1

**Comment by gamma-delta** [comment]
![image](https://user-images.githubusercontent.com/29877714/200907547-4992303f-9cdd-4da1-a4df-d165d89abc98.png)
