### ISSUE TITLE
[1.0 Preview] spells (despite making noise) are not detected by skulk sensors

### ISSUE THREAD

**Issue by CesiumHorizon** [gamma-delta/HexMod#279]

**Comment by CesiumHorizon** [comment]
this seems to also go for the Make Note spell

**Comment by CesiumHorizon** [comment]
update: mishaps also do no trigger it

**Comment by gamma-delta** [comment]
Huh, I wonder if these also trigger the warden.

Casting spells is usually loud, I'd imagine, but

1. Executing a make note anywhere in an artifact will kill the sound
2. if the note attracts the warden... well then >:)

**Comment by gamma-delta** [comment]
whoops, closed and i forgot to mention in the push msg
