### ISSUE TITLE
New pattern rendering code is painfully slow in bulk

### ISSUE THREAD

**Issue by yrsegal** [gamma-delta/HexMod#280]
a few spell circles can bring my fps from a clean 120 to 15

**Comment by Talia-12** [comment]
profile on the rendering code
[Hexal_Forge__runClient__2022_11_11_143959.txt](https://github.com/gamma-delta/HexMod/files/9986590/Hexal_Forge__runClient__2022_11_11_143959.txt)

**Comment by object-Object** [comment]
+1, a mostly full screen of patterns took me from 220 to 15 fps
![2022-11-20_13 45 32](https://user-images.githubusercontent.com/37044997/202920147-e2a38d70-a3a5-4254-95a4-a239f408b50c.png)
![2022-11-20_13 45 41](https://user-images.githubusercontent.com/37044997/202920148-4ae598d7-ff80-472e-b4d7-2be24f00607a.png)

**Comment by object-Object** [comment]
Subjectively, drawing patterns feels much choppier in 0.10.0. Going back to 0.9.6, the grid is noticeably smoother to use. Probably related to this issue.

**Comment by gamma-delta** [comment]
I think I see the problem: it's converting a number in radians to a number in degrees when it doesn't need to be in degrees and then looping over that number as if it were radians, so it's doing like 60x too much work

**Comment by gamma-delta** [comment]
![image](https://user-images.githubusercontent.com/29877714/202931579-2c1f3b5a-ed37-4530-93d4-d5a785a5d854.png)

this was not in fact the problem! it looks like the real problem is we should try to upload things to the GPU as little as possible?

**Comment by gamma-delta** [comment]
(this is from a test with 55 slates on the ground)

**Comment by gamma-delta** [comment]
![image](https://user-images.githubusercontent.com/29877714/202932178-3f3e15d7-4071-44c2-846f-a6a773157157.png)

pros: it runs very fast now

cons: none

**Comment by gamma-delta** [comment]
![image](https://user-images.githubusercontent.com/29877714/202943229-58b4c09c-73eb-4e03-a8c1-4158729d12c7.png)

**Comment by gamma-delta** [comment]
Not calling this fixed yet because I go down to 30fps (from 60) at a field of 121 slates but it is better.
