### ISSUE TITLE
Lists don't wrap their render when nested

### ISSUE THREAD

**Issue by yrsegal** [gamma-delta/HexMod#281]
![2022-11-09_20 21 23](https://user-images.githubusercontent.com/6596492/200977187-c45c9b90-a88b-45a3-9b85-c42b33d7a449.png)

**Comment by yrsegal** [comment]
<img width="369" alt="Screen Shot 2022-11-09 at 8 27 20 PM" src="https://user-images.githubusercontent.com/6596492/200977876-566e8931-05ce-4f7e-8339-7febd7162552.png">
similar problem occurs with ravenmind

**Comment by Talia-12** [comment]
It will also happen if you have a long enough pattern, or an entity with a long enough name, or any iota added by an addon gets too long
