### ISSUE TITLE
[Feature Request] Ability to define custom staff items

### ISSUE THREAD

**Issue by RedRaspberry** [gamma-delta/HexMod#282]
This is mostly because I don't feel it's super fair to ask you guys to add support for every mod adding a wood type ever, but as someone who's helping to make a modpack for some friends and I to play on, it would be nice to have the ability to add custom staffs with a datapack or kubeJS (or config file, etc) of other wood types.
If that *is* fair to ask, then I guess what I really want is a few extra wood staffs for compat with quark (azalea, blossom) & ecologics (azalea, coconut, walnut). I'm sure other people would be happy to have support for BoP and BYG along with [vaguely gestures at all mods that add wood types], I'm just only using quark and ecologics myself lol
I'll even draw some (not amazing, but passable) textures for them if you want!
:)

**Comment by gamma-delta** [comment]
I'm not sure what kind of power KubeJS has these days, but if you can create a new instance of the `ItemStaff` class it just works.

Implementing an extensible wood-type-to-staff registry is currently not something I want to do, but it would be quite easy to make an addon that does it if you want to dip your toes into modding!
