### ISSUE TITLE
Not Enough Iotas Mishap pushes NULL rather than Garbage [1.0] [Bug]

### ISSUE THREAD

**Issue by Talia-12** [gamma-delta/HexMod#283]
![image](https://user-images.githubusercontent.com/17948170/201057691-0bcaff91-9a42-43bc-b8fd-5ce47509f090.png)
Not having enough iotas is pushing nulls rather than garbage to the stack.

**Comment by gamma-delta** [comment]
that's been there since 0.9, good catch!
