### ISSUE TITLE
Augur's Exaltation description incorrect [1.0] [Bug]

### ISSUE THREAD

**Issue by Talia-12** [gamma-delta/HexMod#284]
![image](https://user-images.githubusercontent.com/17948170/201099605-b5732964-22aa-426c-9d24-d5c43cdd2f1f.png)

**Comment by gamma-delta** [comment]
What about it is incorrect?

**Comment by gamma-delta** [comment]
```kt
    override fun execute(args: List<Iota>, ctx: CastingContext): List<Iota> {
        val cond = args.getBool(0, argc)
        val t = args[1]
        val f = args[2]
        return listOf(if (cond) t else f)
    }
```

This is the impl, and this looks like it does what it says in the book, and I also tested it ... am I just brain farting

**Comment by Talia-12** [comment]
ah, nevermind, I read the book incorrectly; I was expecting it to be "keeps the second and discards the third; otherwise keeps the third and discards the second.", and read what's actually there as "keeps the second and discards the third; otherwise keeps the second and discards the third."
My bad 😅
