### ISSUE TITLE
Need localisation for booleans [1.0] [Bug]

### ISSUE THREAD

**Issue by Talia-12** [gamma-delta/HexMod#287]
![image](https://user-images.githubusercontent.com/17948170/201480047-ff659bb9-1d60-49b5-b02a-6a19e1e73354.png)

**Comment by yrsegal** [comment]
``` 
  "hexcasting.tooltip.boolean_true": "True",
  "hexcasting.tooltip.boolean_false": "False",
```
... huh?

**Comment by gamma-delta** [comment]
`return Component.literal(b ? "hexcasting.tooltip.boolean_true" : "hexcasting.tooltip.boolean_false")`

whooooopsy
