### ISSUE TITLE
Cooler Write is able to write True Names

### ISSUE THREAD

**Issue by yrsegal** [gamma-delta/HexMod#288]
as discussed in discord this is probably not ideal

**Comment by yrsegal** [comment]
This isn't resolved, because the discussion in discord was for *any* true names, because otherwise it makes it too easy to steal them.

**Comment by gamma-delta** [comment]
... Why? By giving people trinkets that write things?

I don't see how that's any more powerful than just an akashic record

Where is this discord conversation? I don't think I was a part of it

**Comment by yrsegal** [comment]
The difference is that a focus can bind a cleric circle.

https://discord.com/channels/936370934292549712/1011455473528098857/1037215257015369778

**Comment by gamma-delta** [comment]
Ah right and then you have sentinels

OK good point
