### ISSUE TITLE
Proposed stack operations for 1.0

### ISSUE THREAD

**Issue by gchpaco** [gamma-delta/HexMod#291]
Some of these are in your blogpost.  I'm going to use the Forth terms.

- NIP: ( x1 x2 -- x2 ).
- OVER: ( x1 x2 -- x1 x2 x1 ).
- TUCK: ( x1 x2 -- x2 x1 x2 ).
- 2DUP: ( x1 x2 -- x1 x2 x1 x2).  Particularly useful for paired archer's, architect raycasts.
- PICK: signature complicated.  Basically imagine fisherman's gambit but it copies the iota.

somewhat sketchier and less general but still useful:
- 2OVER: ( x1 x2 x3 x4 -- x1 x2 x3 x4 x1 x2 ).
- 2SWAP: ( x1 x2 x3 x4 -- x3 x4 x1 x2 ).  Swindler's is probably easier to do this.

**Comment by gchpaco** [comment]
Related is the idea of permitting negative offsets for Fisherman's Gambit, with the idea that those stuff the datum deep into the stack.

**Comment by gamma-delta** [comment]
Wait, I don't need to implement nip, we have bookkeeper's
