### ISSUE TITLE
Foci written to by Chronicler's Gambit don't update their display until picked up

### ISSUE THREAD

**Issue by gamma-delta** [gamma-delta/HexMod#292]
It doesn't get the little spark it is supposed to after you cast the spell.

I think it's probably some kind of syncing issue.

(This is on Fabric)

**Comment by yrsegal** [comment]
https://github.com/gamma-delta/HexMod/blob/4aae1ed6b042a1e8e3377418f68a00f497a0004c/Common/src/main/java/at/petrak/hexcasting/common/casting/operators/spells/OpRecharge.kt#L64-L74

This is the solution - you have to *set* the stack, not update in place

**Comment by gamma-delta** [comment]
whoops fixedin 274bec1
