### ISSUE TITLE
[Potential Bug] Some actions don't execute when bloodcasting using a pre-made series of patterns

### ISSUE THREAD

**Issue by booleancoercion** [gamma-delta/HexMod#297]
Game version is Fabric 1.18.2.

We've had a bit of a discussion on discord about this, but here's the deal:
I made a spell that throws a player up in the air and immediately shrinks them, and put it in my spellbook. Here's an image:
![image](https://user-images.githubusercontent.com/33005025/202590596-03c7cf53-b889-4682-b15f-4d5dff1f4958.png)

When casting each of the patterns manually in succession, it works as intended (albeit without the immediate part which was meant to kill the target, but oh well). The weird part is that when casting it from the book __when you don't have media in your inventory__, i.e. reading and executing, the player only gets thrown upwards without being shrunk.

When I added sufficient media to my inventory it worked as intended. @yrsegal noticed this and said that it looked like a bug, so I posted about it here.

**Comment by gamma-delta** [comment]
I think this should have been closed by #329? If it doesn't let me know.
