### ISSUE TITLE
Chronicler's Gambit is called Chronicler's Prfn. in the book, and its description overflows slightly at the bottom

### ISSUE THREAD

**Issue by object-Object** [gamma-delta/HexMod#299]
![image](https://user-images.githubusercontent.com/37044997/202917053-2f8adf79-a85b-4cfd-8d64-cb13f97b6837.png)

The actual Chronicler's Purification title also overflows a bit. Maybe the wrong one got changed?

~~And just as a related side note, Chronicler's Gambit's arguments seem to break convention, no? Compare to the casting item patterns and Akasha's Gambit, where the target entity/location is first in the list.~~ Actually the arguments are just the wrong way around in the book.

Version: 0.10.0

**Comment by gamma-delta** [comment]
"get 0.10.0 out quick" i said "it will be fun" i said "move fast and break things" i said
