### ISSUE TITLE
Prospecter's Gambit should be spelled Prospector's Gambit

### ISSUE THREAD

**Issue by object-Object** [gamma-delta/HexMod#300]
![image](https://user-images.githubusercontent.com/37044997/202917649-e6e2d0f7-9548-41f5-8605-63fbf81d6cb2.png)
https://www.dictionary.com/browse/prospector

Version: 0.10.0

**Comment by gamma-delta** [comment]
fuck

**Comment by gamma-delta** [comment]
The worst part is i already spelled it right once

https://github.com/gamma-delta/HexMod/blob/30dc2e93c82fb7563cb4a1c1b69f304a21aa82c5/Common/src/main/resources/assets/hexcasting/lang/en_us.json#L1123
