### ISSUE TITLE
Erase Item can no longer erase slates

### ISSUE THREAD

**Issue by object-Object** [gamma-delta/HexMod#303]
![2022-11-20_13 58 17](https://user-images.githubusercontent.com/37044997/202920796-c9aef71a-2fc4-4f49-bbfa-170f922d5767.png)

Version: 0.10.0

**Comment by gamma-delta** [comment]
Could it ever? (I'll fix it anyways)

**Comment by object-Object** [comment]
Yeah, it could in 0.9.x (tested on 0.9.6 at least)
