### ISSUE TITLE
Crash when creating a new world on Fabric 1.19

### ISSUE THREAD

**Issue by Ryminer2** [gamma-delta/HexMod#307]
Title. No other mods installed except for Hexcasting dependencies. Also applies when loading into an existing world.

[crash-2022-11-20_20.34.00-server.txt](https://github.com/gamma-delta/HexMod/files/10051831/crash-2022-11-20_20.34.00-server.txt)

**Comment by gamma-delta** [comment]
Please upload the crashlog to Pastebin or Github Gist or similar first

**Comment by Ryminer2** [comment]
...I put the crash log right there? But alright.

https://pastebin.com/Vi8G5QdT

**Comment by Talia-12** [comment]
CardinalComponents is missing from the fabric.mod.json dependencies section
```json
  "depends": {
    "minecraft": "=1.19.2",
    "java": ">=17",
    "fabricloader": ">=0.14",
    "fabric": ">=0.64",
    "fabric-language-kotlin": ">=1.7.4+kotlin.1.6.21",
    "patchouli": ">=1.19.2-77",
    "paucal": "0.5.x"
  },
```

**Comment by gamma-delta** [comment]
ah yeah that'd do it, good catch. (Why did I do that? What was I thinking?)
