### ISSUE TITLE
Guidebook spoilers on new world

### ISSUE THREAD

**Issue by IcarusWhite** [gamma-delta/HexMod#308]
Created new world on 1.19 with Create 0.10
(edit: problem persists in v0.10.1)
Expected: guidebook would only have introduction unlocked, and would unlock with advancements.
Result: everything is visible, even the spoilers!
Also, things look "weird". Are the "icons" broken? See attached.
![2022-11-20_20 45 21](https://user-images.githubusercontent.com/74292622/202943460-7d9b21ab-db1a-487f-b095-2c7dbe09686c.png)
![2022-11-20_20 46 32](https://user-images.githubusercontent.com/74292622/202943510-c057a75a-f87f-494b-8dd4-6deab4c24c42.png)

**Comment by gamma-delta** [comment]
Whoops, the unlock is probably because I haven't rerun datagen in a billion years.

The broken text is a Patchouli problem, and the chamfered intersections is for accessibility (so you can actually read the pattern's stroke order). I think the Patchouli fix is to resize the book on the landing page.

**Comment by gamma-delta** [comment]
Can you show your advancements screen, also?

**Comment by IcarusWhite** [comment]
Edit: Created a new world on v0.10.1, problem persists.
Mods are Enigmatica 9 v.1.2.0 (https://www.curseforge.com/minecraft/modpacks/enigmatica9/files/4091410) plus Hex Casting v0.10.1.
There are no Hex Casting advancements unlocked yet:
![2022-11-24_01 35 04](https://user-images.githubusercontent.com/74292622/203711400-1e677e31-b0a5-4777-97f5-393c71cd8002.png)
However, the book is fully unlocked. For example, the Mind Flay entry:
![2022-11-24_01 35 20](https://user-images.githubusercontent.com/74292622/203711410-9d5c062f-953b-4a53-820e-e8ca6bd584a7.png)

**Comment by SamsTheNerd** [comment]
i haven't heard or seen of this before so I'm guessing it got fixed ?
