### ISSUE TITLE
Localization issues on v0.10

### ISSUE THREAD

**Issue by IcarusWhite** [gamma-delta/HexMod#309]
Some of the spell localization is broken, causing the names of e.g. Ancient Scrolls to display strangely.
![2022-11-20_21 17 17](https://user-images.githubusercontent.com/74292622/202946525-212be844-8dc4-4b2d-87f3-f74bff44bce7.png)
(Note: this occured on a custom modpack. I will attempt to check later whether this is a more general problem.)

**Comment by gamma-delta** [comment]
*what*

oh god that's a dumb error hold on

**Comment by gamma-delta** [comment]
For anyone coming here later, run `/hexcasting recalcPatterns` to fix it, new scrolls should generate properly
