### ISSUE TITLE
Can't cast great spells??

### ISSUE THREAD

**Issue by IcarusWhite** [gamma-delta/HexMod#310]
Attempting to cast a great spell from an ancient scroll (or with the scroll's pattern) causes a strange error instead of attempting to cast.
![2022-11-20_21 55 51](https://user-images.githubusercontent.com/74292622/202953671-463fb54a-1e5c-468f-bdbc-19c576a47c6a.png)

**Comment by gamma-delta** [comment]
Whoops. Try running `/hexcasting recalcPatterns` first and see if that helps.

Incidentally, is this a new world? And are you on Forge or Fabric? (I ask because some people on the discord are having the same problem.)

**Comment by IcarusWhite** [comment]
Update. After a suggestion, running /hexcasting recalcPatterns allowed the spell to be cast.
This command requires OP to run.
Ideally, this shouldn't be necessary...

**Comment by gamma-delta** [comment]
Whoops, closed when I closed #309
