### ISSUE TITLE
Can't trigger Enlightenment (spoilers!)

### ISSUE THREAD

**Issue by IcarusWhite** [gamma-delta/HexMod#311]
Attempting Enlightenment, by casting a single spell from health, going from full to very low (<0.5 hearts?), after Blind Diversion.
Specifically, attempted casting WSZ with duration 2.49 and power 2, and then duration 2.5 and power 2.
Expected: duration 2.49 unlocks Enlightenment.
Result: duration 2.49 fails with "am I not skilled enough?"
duration 2.50 kills me, and also fails with "am I not skilled enough?"
edit: forge v0.10

**Comment by gamma-delta** [comment]
You can't use a great spell to achieve enlightenment.
