### ISSUE TITLE
Casting sound playing for every pattern executed [Bug] [0.10]

### ISSUE THREAD

**Issue by Talia-12** [gamma-delta/HexMod#312]
The new way that casting sounds happen result in the sound occurring once per pattern executed rather than once per right click of the trinket, or pattern drawn, so executing more than one pattern at once (any trinket, or a hermes/thoth of something with the staff) sounds reallll bad

**Comment by gamma-delta** [comment]
Closed by [76006d7](https://github.com/gamma-delta/HexMod/commit/76006d72dcb9f2020eda60e7f3aa468953ac0fed)
