### ISSUE TITLE
[1.19 Fabric] Instant crash/freeze when attempting any Hex Spell

### ISSUE THREAD

**Issue by ImAK9** [gamma-delta/HexMod#313]
Mod, fapi & deps versions are in the log.

Log: https://aofpaste.com/ebetiqazuc.yaml

**Comment by gamma-delta** [comment]
Duplicate of #276 (tl;dr: install adoptium openjdk)

**Comment by gamma-delta** [comment]
Whoops apparently this is with openjdk. Also TIL normal users can't reopen issues themselves.

**Comment by gamma-delta** [comment]
OK we switched to Cloth config it should work now
