### ISSUE TITLE
Wall scroll changes color depending on the angle you look at it from

### ISSUE THREAD

**Issue by gamma-delta** [gamma-delta/HexMod#314]
![image](https://user-images.githubusercontent.com/29877714/203118894-579fa85a-6c41-44e6-9451-3c19be62e5e5.png)

![image](https://user-images.githubusercontent.com/29877714/203118948-83779372-bd7f-4fe1-b1f4-413be4ba0d03.png)

**Comment by SamsTheNerd** [comment]
seems to be fixed in #503 ?
