### ISSUE TITLE
Unifying Distillation Broken [Bug] [0.10]

### ISSUE THREAD

**Issue by Talia-12** [gamma-delta/HexMod#317]
When doing unifying distillation of `[0, 1, 2]` with `[0, 1, 2]`, rather than the output being `[0, 1, 2]` it is
```
[]
2
1
0
```
This is probably because in the line
```kotlin
list1 + list2.filter { x -> list1.none { Iota.tolerates(x, it) } }.asActionResult
```
there needs to be brackets around the list addition so that asActionResult applies to the sum of the lists, rather than taking the first list and adding it to the second list as an action result
e.g.
```kotlin
(list1 + list2.filter { x -> list1.none { Iota.tolerates(x, it) } }).asActionResult
```

**Comment by gamma-delta** [comment]
i wish all [Languages where open braces are lambdas] a very [Die]
