### ISSUE TITLE
Game does not launch with Hexcasting 0.10.1 installed on Fabric

### ISSUE THREAD

**Issue by Ryminer2** [gamma-delta/HexMod#319]
Game crashes before the window even appears with the latest release.
https://pastebin.com/MerkBC6Y

Mods installed:

Fabric 0.14.10
Fabric API 0.67.0
Fabric Language Kotlin 1.8.6
Patchouli 1.19.2-77 Fabric
Paucal Fabric 0.5.0

**Comment by Talia-12** [comment]
After reading the pastebin, It seems like this crash is the result of something expecting [Cloth Config](https://www.curseforge.com/minecraft/mc-mods/cloth-config) to be installed even though it is intended to be an optional dependency.

**Comment by Ryminer2** [comment]
Can confirm this fixes it.

**Comment by gamma-delta** [comment]
Whoops, that's on me. Hold on a second

**Comment by gamma-delta** [comment]
I'm just going to make it mandatory rather than try and finagle a wrapper class

**Comment by gamma-delta** [comment]
whoops last commit should have fixed it
