### ISSUE TITLE
Toolsmith Impetus crashes game

### ISSUE THREAD

**Issue by GameGuruGreenGryphon** [gamma-delta/HexMod#32]
Crash report: https://gist.github.com/GameGuruGreenGryphon/51deb6267d2f8c1b10b8d5f3d89ece6c

### How to recreate
Go to singleplayer (haven't tested on a server)
Place one toolsmith impetus and place any number of spell circle valid blocks greater than two so a spell circle can start to be formed and "register" these blocks
Break any valid spell circle block that was previously registered correctly before the spell circle casts
When the next block is attempted to be registered, particles appear over the broken block that indicate the spell circle failed to compile and will then crash your game

Does not need any data stored in these blocks

**Comment by gamma-delta** [comment]
Working on a fix right now and I discovered some related issues, I'll fix it in the morning
