### ISSUE TITLE
Cannot enlighten self

### ISSUE THREAD

**Issue by IcarusWhite** [gamma-delta/HexMod#320]
Version: forge 0.10.1
Instructions: After getting Blind Diversion, cast from health, from full health, to less than half a heart.
Specifically, at 10 hearts, cast White Sun Nadir for 49.9 seconds at power 2.
Expected: Enlightenment.
Result: Reduced to (less than?) half a heart, and got weakness. But no enlightenment.

**Comment by gamma-delta** [comment]
I really don't know what you could be doing here, because I managed with Black Sun's Nadir(1, 19.5) just fine...

What's your modlist?

**Comment by IcarusWhite** [comment]
Update: I'm quite confused.
Doing what you said worked, but only after I tried it a few times???
One of the mods in this modpack, apotheosis, can increase my health; I'm wondering whether some sort of desync is at work here.
It worked after I tried taking minor fall damage and healing.
I'm not sure what is going on here, but whatever I did worked, for now.
