### ISSUE TITLE
Greater teleport causes dedicated server to hang indefinitely when teleporting to unloaded chunks

### ISSUE THREAD

**Issue by Flyte-less** [gamma-delta/HexMod#327]
Using version 0.9.4 on forge.

When using the spell long distance it can consistently cause the server to enter a frozen state, forcing every player to time out. The only way to recover from this state is by force killing the server process.

Notes: 
It seems that if the destination chunk is loaded the greater teleport will not cause a server crash, regardless of how many of the surrounding chunks are loaded as well

The built in /tp command does not seem affected.

Lowering the render and simulation distances to the very lowest seems to mitigate this issue.

[Modlist if relevant.](https://gist.github.com/Flyte-less/fd200285ebb2e4eecad501a1538b9922) No logs or crash reports to provide as the server is unable to record anything during it's frozen state.

Apologies if this isn't super helpful, I only have one dedicated server and was unable to replicate this bug in singleplayer.

**Comment by Flyte-less** [comment]
One more piece of information that I hope is useful. Remember how I said that lowering the render distance seemed to help? Well it looks like doing that causes none of the surrounding chunks to appear even after setting the render distance back to normal.

![image](https://user-images.githubusercontent.com/83427235/204070838-bfbbd817-c6e3-4063-ab75-3417ea3515f0.png)

Relogging or spamming the render distance option seems to fix it though.

**Comment by gamma-delta** [comment]
That looks to me like your server just doesn't have enough memory to load those chunks that quickly ... but I'm not sure how come `/tp` doesn't crash, then. Lemme take a look.

**Comment by gamma-delta** [comment]
That should fix it but let me know if it doesn't.

**Comment by St0rmC4st3r** [comment]
> That should fix it but let me know if it doesn't.

Letting you know that it doesn't. Playing TNP Limitless 5 2.30.0. Minecraft version: 1.18.2. Forge version: 40.2.0.
Seems to hang the server inconsistently, as in, sometimes it does unhang, and sometimes it hangs indefinitely.
I also tried claiming and loading the chunks via FTB Chunks, but this doesn't seem to affect the bug.

**Comment by redstonerblast** [comment]
This bug is still occurring to me in 1.20.1
