### ISSUE TITLE
Bloodcasting doesn't round up

### ISSUE THREAD

**Issue by yrsegal** [gamma-delta/HexMod#329]
https://github.com/gamma-delta/HexMod/blob/main/Common/src/main/java/at/petrak/hexcasting/api/spell/casting/CastingHarness.kt#L544

This should have a `ceil` attached to it. Otherwise, small costs have trouble being bloodcast.

**Comment by yrsegal** [comment]
oops, I didn't use a permalink...

https://github.com/gamma-delta/HexMod/blob/de8e84cdbd305836792ca456d95528c23c3f8c3d/Common/src/main/java/at/petrak/hexcasting/api/spell/casting/CastingHarness.kt#L545

this is the line that needed the `ceil`.

**Comment by yrsegal** [comment]
This "fix" will allow free bloodcasting of any cost below half a heart, and should be reverted

**Comment by yrsegal** [comment]
This still doesn't fix costs like 3.5, though. That'll just fail, even though it'll take 3 health. I said ceil for a reason

**Comment by gamma-delta** [comment]
No, it doesn't. I just checked.
