### ISSUE TITLE
Grayscale pigments not visually distinct enough from eachother as summoned blocks

### ISSUE THREAD

**Issue by GameGuruGreenGryphon** [gamma-delta/HexMod#34]
![javaw_quWR9sEPgk](https://user-images.githubusercontent.com/87587913/160251764-47ba4bf8-15d3-487e-9766-418eacda3d8a.png)
From left to right is the white pigment, light gray pigment, gray pigment, and black pigment.
They only differ in alpha levels, where white is 100% alpha and black is 0% alpha.

While the white through gray pigments might not cause many issues, using the black pigment gives noticeably less feedback from successfully casting spells, casting spells from spell circles, and summoning blocks, because the particles never show up.

I'd label this issue as minor.

### Suggestion
Maybe have a separate pigment that's only invisible, and not a color?

**Comment by gamma-delta** [comment]
Wire fixed this ages ago (black pigments now have a pearlescent sheen) and we just never closed the issue whoopsy
