### ISSUE TITLE
No data fixer registered 

### ISSUE THREAD

**Issue by SylisMC** [gamma-delta/HexMod#341]
Noticed this in my logs
hexcasting-fabric-1.19.2-0.10.2.jar
[20:31:28] [Render thread/ERROR]: No data fixer registered for hexcasting:wall_scroll

**Comment by gamma-delta** [comment]
Data fixer upper is Mojang's tool for making sure worlds from old versions work in new versions. It's not a goal of mine to have Hexcasting work across versions, so there's nothing to be worried about there.

I do wonder how you can turn that off, though...
