### ISSUE TITLE
[Bug] [0.10.3] Sealed focus recipe doesn't work on Forge

### ISSUE THREAD

**Issue by object-Object** [gamma-delta/HexMod#347]
Tested on Forge 43.1.7 if it matters. Screenshot shows a full stack of honeycomb, but it also happens with a single one.
![image](https://user-images.githubusercontent.com/37044997/205543842-97aecfb6-774c-4b0b-ac11-4932c3ea026b.png)

**Comment by gamma-delta** [comment]
It also doesn't work on Fabric i just found out

**Comment by object-Object** [comment]
Fixed as per #360 (according to Petra)
