### ISSUE TITLE
using a wand crashes my game (1.18.2 - fabric)

### ISSUE THREAD

**Issue by Knipppi** [gamma-delta/HexMod#354]
anytime i use a wand it opens the grid thing for casting but as soon as i click on the dot to start the casting process it crashes my game. i thought i might be because of the shader, but no. i even tried installing the newer version of it, same results.

**Comment by gamma-delta** [comment]
Probably a duplicate of #276

**Comment by gamma-delta** [comment]
Closed for inactivity, I suppose

If that didn't solve your problem just comment here again
