### ISSUE TITLE
Dyeable trinkets and spellbooks would be super nice

### ISSUE THREAD

**Issue by gchpaco** [gamma-delta/HexMod#366]
Right now the only difference between various trinkets is the name.  It would be really nice to be able to dye them, say with the pigment system, so that you can visually distinguish them without putting your mouse over them.  Ditto spellbooks.

**Comment by gchpaco** [comment]
gattsuru hacked something together that required a ton of JSON for the Arcane Compendium's server.  I think it was https://github.com/gattsuru/HexMod/tree/VeryJsonHeavyDyableItems that may be a useful basis for starting.

**Comment by SamsTheNerd** [comment]
covered by next hexgloop update's dyeable books + next hex update's cad/spellbook skins.
