### ISSUE TITLE
block.hexcasting.conjured_block is not translated

### ISSUE THREAD

**Issue by Ch1216** [gamma-delta/HexMod#368]
You can see this when you look at a conjured block via a waila like mod, I use Jade (1.18.2)

**Comment by Ch1216** [comment]
Please reopen, it is undefined/unstranslated again in forge 1.19.2 0.10.3

**Comment by object-Object** [comment]
The issue is fixed on 1.20.1 / 0.11.x; this isn't really a critical enough bug to be worth backporting.
