### ISSUE TITLE
Unreadable font in Russian

### ISSUE THREAD

**Issue by WABUHA** [gamma-delta/HexMod#369]
problem in title (is there a way to change the font in the book, or increase it?)
this is with unicode fonts off:
![image](https://user-images.githubusercontent.com/51258962/211549655-3528ae11-51ed-4bd4-8de6-475f986f823d.png)
this is with force unicode font on:
![image](https://user-images.githubusercontent.com/51258962/211550567-44e7aa8a-37d5-4219-aaa9-55cc84f5d2ab.png)
better, but still not everything is clear what is written
resolution is 1920x1080

**Comment by HyperSoop** [comment]
i think there definitely is a way to increase the scale of the book, look at the main page

**Comment by gamma-delta** [comment]
Unfortunately, that's a Patchouli issue :(

You can change the scale of the book by clicking the two-arrows button on the landing page, on the left side.
