### ISSUE TITLE
[Bug?] Arrows stuck in blocks still have velocity with Pace Purification

### ISSUE THREAD

**Issue by object-Object** [gamma-delta/HexMod#370]
This is probably just the data that Minecraft gives, thanks Mojank. But it would be helpful and more intuitive if there were a special case for Pace Purification for arrows stuck in blocks to have zero velocity.

**Comment by gamma-delta** [comment]
![image](https://user-images.githubusercontent.com/29877714/213898511-d65fc6e9-407e-454d-9a6d-e25c4a80551d.png)

**Comment by object-Object** [comment]
Note: this apparently _can_ be worked around (by raycasting from the arrow's position using its velocity and seeing if the resulting position is within a block) so it may or may not be necessary to patch this.
