### ISSUE TITLE
Assessor's Reflection uses 1 item on the stack, when it should use 0

### ISSUE THREAD

**Issue by ChloeTax** [gamma-delta/HexMod#375]
![javaw_ZUWkGyHEJO](https://user-images.githubusercontent.com/119641630/212809876-51edd24e-e094-401a-bb7f-c254b9589870.png)
![javaw_twYVWm3Xwf](https://user-images.githubusercontent.com/119641630/212810347-d8681737-a260-4b84-bc04-5015019888a2.png)

**Comment by gamma-delta** [comment]
Ah, it's misdocumented ... right now it takes the top iota off the stack, tries to save it, and tells you if it succeeded.

Not sure if that behavior or the documented behavior is better, to be honest, I feel like there would be some bad surprises with trying to assess abacuses and scrolls. But I'm going to change it to the docced behavior.
