### ISSUE TITLE
Flay any entity's mind into a spawner block

### ISSUE THREAD

**Issue by HyperSoop** [gamma-delta/HexMod#376]
Let one specify a spawner instead of amethyst as a destination block for mind flaying, and choose any entity for this. This would be a very good other use for the spell, letting people make spawner farms for mobs not naturally occuring in spawners.

**Comment by SamsTheNerd** [comment]
could maybe be done with the new 1.20 flay any entity stuff. might require a way for a block/block entity to receive what entity was flayed into it. Otherwise sounds like something good for an addon.
