### ISSUE TITLE
[0.11-pre] Mishap pattern names should be more distinct from the rest of the message

### ISSUE THREAD

**Issue by object-Object** [gamma-delta/HexMod#379]
For example:
![image](https://user-images.githubusercontent.com/37044997/213894990-7a1547fc-744c-4366-aacc-965ed21ea8d9.png)
I think the pattern name should be a different colour, maybe the yellow/gold used in patterns iotas, so it's more distinct from the error message. Right now it kind of just blurs together.

**Comment by gamma-delta** [comment]
Also fixed in previous commit
