### ISSUE TITLE
The particles generated by spell circles cannot be seen through colored or tinted glass

### ISSUE THREAD

**Issue by CesiumHorizon** [gamma-delta/HexMod#38]
I have also included a picture of my video settings and the log file if that helps
[latest.log](https://github.com/gamma-delta/HexMod/files/8357228/latest.log)
![image](https://user-images.githubusercontent.com/102282325/160273947-03533fbe-3fc3-4ba2-8013-fa13d1c00031.png)
![image](https://user-images.githubusercontent.com/102282325/160274016-d4f8f4e4-55d8-46c7-830a-3404c888434f.png)
![image](https://user-images.githubusercontent.com/102282325/160274030-78b381fa-c317-4b35-a112-55b6bd67a50a.png)
![image](https://user-images.githubusercontent.com/102282325/160274038-7c3b6843-1a54-4656-acfc-ab40bfdb99a9.png)
![image](https://user-images.githubusercontent.com/102282325/160274068-0cc3ade6-fbe8-431f-9981-4b476cceeadb.png)

**Comment by gamma-delta** [comment]
Are you using Optifine, Sodium, or any other mods that mess with graphics like that?

**Comment by CesiumHorizon** [comment]
Im only using the mods that hexcasting requires
also im using the curseforge launcher if that helps
heres a picture of the mods folder:
![image](https://user-images.githubusercontent.com/102282325/160837450-75360530-2ac7-4bd2-a746-f1964e293171.png)

**Comment by CesiumHorizon** [comment]
after a bit of searching it turns out this is actually a relatively new minecraft feature and to see the particles through colored glass you need to enable "fabulous" graphics
