### ISSUE TITLE
[0.10] Clearing akashic libraries with shift right click doesn't remove the pattern or lens info

### ISSUE THREAD

**Issue by object-Object** [gamma-delta/HexMod#381]
![image](https://user-images.githubusercontent.com/37044997/213895392-177aef7f-c9d3-48a1-9d6b-225088e17b78.png)
Reading from that pattern returns null as expected.

**Comment by Talia-12** [comment]
Okay, found the problem that's causing this. Basically, when the bookshelf's pattern is cleared it sets its pattern and iota to null. When getting serialised to send over to the client, if the pattern or iota are null it doesn't bother adding anything to the CompoundTag that it's sending across. *But*, when the ClientboundBlockEntityDataPacket sees that you want to send across an empty compound tag, it helpfully optimises and sets the tag to null, and when IForgeBlockEntity receives the packet, if the tag is null it doesn't bother calling the BlockEntity's .load method.

So it seems like the way to fix this is basically to attach some dummy data to the CompoundTag if nothing else is in it.
