### ISSUE TITLE
[Suggestion] Don't close the grid if the stack is empty but the ravenmind isn't

### ISSUE THREAD

**Issue by object-Object** [gamma-delta/HexMod#393]
I often start staff-casted hexes by putting something in the ravenmind, only for the grid to close, followed by a facepalm, then drawing the same thing again but preceded by Nullary Reflection this time. It'd be nice if the auto-grid-close could respect the ravenmind as well.

**Comment by macks2008** [comment]
In more general terms, it should only close and clear the grid if the entire "program state" of the hex is empty. This is doubly true if the ignored Ravenmind Iota then gets cleared BECAUSE it was ignored.

**Comment by gamma-delta** [comment]
I think @macks2008 that should be a different issue. But yeah it is a good point.
