### ISSUE TITLE
[0.10.3] Configs don't persist through restarts

### ISSUE THREAD

**Issue by object-Object** [gamma-delta/HexMod#398]
Using Fabric.
* Change a config option in Mod Menu (tested with denied actions)
* Try the configured thing, see that it changed
* Restart your game
* Try the configured thing / look at Mod Menu, see that it reverted to the default

**Comment by maraxin** [comment]
From what I saw, only list with disallowed spells and spell circles are being cleared, the first setting (about break block spell) does not being reverted

**Comment by maraxin** [comment]
Late here, but it's only fabric issue

**Comment by object-Object** [comment]
Seems like this doesn't occur when using GsonConfigSerializer instead of JanksonConfigSerializer. Not sure if there's another way to fix it.
https://github.com/gamma-delta/HexMod/blob/4b8c91505426817050082bcd1cf709abf357b079/Fabric/src/main/java/at/petrak/hexcasting/fabric/FabricHexConfig.java#L41
