### ISSUE TITLE
Wand doesn't show spellbook page number

### ISSUE THREAD

**Issue by Roseplate** [gamma-delta/HexMod#4]
when scrolling the spellbook in the wand the page number doesn't show, only hex.spellbook.tooltip.page, same with hovering over the spellbook, I think it might be because it's just "hex" instead of "hexcasting" but I can't check (my IDE isn't playing nice)

**Comment by gamma-delta** [comment]
Closed by 65acd40!

**Comment by gamma-delta** [comment]
(Is that Vivenna?)

**Comment by Roseplate** [comment]
yeah, it is! it's by Shuravf, I just commandeered the picture
