### ISSUE TITLE
[Bug] Sticky teleportation has never worked

### ISSUE THREAD

**Issue by object-Object** [gamma-delta/HexMod#402]
Repro steps:
- Sit on a horse/pig
- Teleport either yourself or the pig (I used `(10, 0, 0)`)
- Only the selected entity is teleported, not the entire stack

Tested on Fabric 0.10.3, 0.9.6, and 0.9.2, and Forge 0.10.3, 0.9.6, and 0.9.4.
See also: #186

**Comment by gamma-delta** [comment]
I'm just gonna remove this whole mechanic, no one uses it and it's dumb

**Comment by object-Object** [comment]
maybe people would use it if it worked? i think it's a neat tradeoff to get no drop teleporting but have to manage a living mob

**Comment by luo-zi** [comment]
> 如果它有效，也许人们会使用它？我认为这是一个巧妙的权衡，没有掉落传送，但必须管理一个活生生的生物

oh we can use the ender pearl to get this purpose, just throw it into a area of rising bubbles,   we can teleport it to any place that we want to go.

**Comment by Ch1216** [comment]
This resurfaced in 0.11.3
on forge 47.5.12
Tested with a saddled pig
