### ISSUE TITLE
Cyphers, Trinkets, and Artifact crafting recipes don't make sense

### ISSUE THREAD

**Issue by GameGuruGreenGryphon** [gamma-delta/HexMod#41]
Cyphers take 8 copper ingots and 1 amethyst dust to craft, trinkets take 8 iron ingots and 1 amethyst shard to craft, and artifacts take 3 gold and 1 music disc to craft.
Even though copper is common, the recipe seems a bit too much for what cyphers are.
8 iron for trinkets is pretty rough considering how many trinkets you might want or need, probably less bad than how much you need hoppers, though.
3 gold seems like a weird amount for artifacts considering the rest take at least 8 items surrounding the center piece for crafting.

**Comment by gamma-delta** [comment]
Whoops that was a bug from porting things to Paucal.
