### ISSUE TITLE
Scribe's Gambit not functioning with scrolls or slates

### ISSUE THREAD

**Issue by RussianPercussion** [gamma-delta/HexMod#410]
Works on a focus but when used on a scroll or slate, returns "Scribe's Gambit: needs a place that will accept 'pattern' in other hand but got 'scroll/slate'.  Tested in fabric version 1.19.2-0.10.3.

**Comment by Soliel** [comment]
I'm testing this in the same version of the mod, but I can't reproduce this. Which pattern/s failed for you?

**Comment by RussianPercussion** [comment]
I tried

**Comment by RussianPercussion** [comment]
I tried with a few different ones, with and without the "parentheses" hexes. I thought I read something about it not working with mind's reflection but would there be other restrictions or things I could be doing wrong?

**Comment by gamma-delta** [comment]
Were you writing to an already written slate/scroll? And were you writing a *list* of patterns, or the pattern itself?

You should be using Consideration, not Introspection/Retrospection. Go `Introspection, <the pattern you want>, Scribe's Gambit`
