### ISSUE TITLE
Assessor's Reflection accidentally takes an argument

### ISSUE THREAD

**Issue by Math321** [gamma-delta/HexMod#418]
Using Hexcasting 0.10.3, if you cast Assessor's Reflection with an empty stack, it mishaps, saying "Assessor's Reflection expected 1 or arguments, but the stack was empty". If your stack is not empty, it eats whatever iota is on the top of the stack and returns the value the Reflection should normally return.

**Comment by gamma-delta** [comment]
Duplicate of #375
