### ISSUE TITLE
Console overcasting message printing 5 times instead of 1

### ISSUE THREAD

**Issue by GameGuruGreenGryphon** [gamma-delta/HexMod#42]
### Log:
https://gist.github.com/GameGuruGreenGryphon/51abfa23aec3c6744e176d35ecce5c24
Singleplayer world

### How to reproduce:
Be in survival mode
Have no media in your inventory
With a staff or empty artifact, write or cast a spell that takes media to cast

**Comment by gamma-delta** [comment]
Oops I forgot to remove that! That was a debug log I meant to remove after implementing overcasting
