### ISSUE TITLE
Empty directrix does not work with vertical slates

### ISSUE THREAD

**Issue by Robotgiggle** [gamma-delta/HexMod#425]
If an empty directrix receives a circle pulse and the only available output slates are vertical (ie placed on a wall as opposed to on the ground) the pulse will immediately end and the empty directrix will emit mishap particles. This does not happen with Mason Directrices, only the empty kind.

Here's an example. The circle on the left will function as expected, randomly picking one of the two paths. The circle on the right will mishap and halt as soon as it hits the directrix.
![2023-02-25_01 54 21](https://user-images.githubusercontent.com/88736742/221343642-8b49aad1-8368-460c-8ac5-ac5a73cd3d0a.png)

**Comment by Talia-12** [comment]
has been fixed at some point on the latest dev release by all the spell circle changes.
