### ISSUE TITLE
"Delve Too Deep" mishap grants infinite air if triggered when you're already drowning

### ISSUE THREAD

**Issue by beholderface** [gamma-delta/HexMod#428]
Forge, 0.10.3
This persists when you leave the body of water, and in my testing did not go away until I used /kill.
To reproduce:
   Be drowning (you might have to already have taken damage, not sure)
   Cast the following:
      Introspection
      Gemini Decomposition
      Hermes' Gambit
      Retrospection
      Gemini Decomposition
      Hermes' Gambit

**Comment by Talia-12** [comment]
seems like this got fixed at some point, no longer an issue in the latest dev version
