### ISSUE TITLE
HexCoord uses the wrong formula for s

### ISSUE THREAD

**Issue by object-Object** [gamma-delta/HexMod#429]
https://github.com/gamma-delta/HexMod/blob/a3b62c4ab8a653217ac5f1ea0607e7aa23e0f8b5/Common/src/main/java/at/petrak/hexcasting/api/casting/math/HexCoord.kt#L11

Per [Red Blob Games](https://www.redblobgames.com/grids/hexagons/#coordinates-axial), `s = -q - r`. The above line is missing a minus sign on `this.s`.

**Comment by Talia-12** [comment]
changed, thankfully it seems like s() literally isn't used anywhere so this shouldn't have been causing any issues.
