### ISSUE TITLE
In 1.18 hex (0.9.6) bloodcasting fails when the player has more than 32 HP

### ISSUE THREAD

**Issue by yoyotam3** [gamma-delta/HexMod#430]
Bloodcasting seems to have extremely strange behaviours when I try to cast spells with Hermes Gambit while having more than 32 hp (16 hearts). Spells seem to fail after executing at the first pattern that requires any media (even negligible). So if execute a spell that goes Mind's Reflection>Compass' Purification>Mind's Reflection>Alidade's Purification>Archer's Distillation>Mind's Reflection>Mind's Reflection>Mind's Reflection with Hermes' Gambit, the stack will only contain the raycasted vector, not any of the player references that should have been added after. Not sure if it matters since I'm pretty sure all mods affect the same HP stat but the hp comes from SoL:Carrot Edition

**Comment by yoyotam3** [comment]
Manual casting works perfectly fine by the way, it's just the automatic casting from lists of patterns that breaks

**Comment by gamma-delta** [comment]
This is a known bug I'm pretty sure and I'm not maintaining 1.18 any more. ... Sorry about that.

**Comment by yoyotam3** [comment]
I think the bug might have been fixed but never got actually released on curseforge? https://github.com/gamma-delta/HexMod/issues/329 mentions a fix but that was done nov 30 and the last curseforge release is nov 9? Not sure

**Comment by yoyotam3** [comment]
oh wait no that fix was for 1.19
