### ISSUE TITLE
[FEATURE] Configurable Spawn Rate and Location for Scrolls

### ISSUE THREAD

**Issue by Noobulus** [gamma-delta/HexMod#44]
The ability to tweak where and how Hex scrolls spawn in chest loot would be useful for pack development. Packdevs could gate Hex later in a pack, make scrolls scarcer to incentivize exploration, or tweak where scrolls spawn (for example, a custom loot table for a special Hex ruins structure).

**Comment by gamma-delta** [comment]
You can do this with a datapack I'm pretty sure
