### ISSUE TITLE
Dividing a vector by a number checks if the numerator is zero, not the denominator

### ISSUE THREAD

**Issue by object-Object** [gamma-delta/HexMod#446]
https://github.com/gamma-delta/HexMod/blob/a3b62c4ab8a653217ac5f1ea0607e7aa23e0f8b5/Common/src/main/java/at/petrak/hexcasting/common/casting/operators/math/OpDivCross.kt#L35

Pretty sure this line should be checking if `rnum == 0`. The current code results in a mishap if dividing the zero vector by a nonzero number (result should be the zero vector), and no mishap if dividing a vector by zero (should mishap).

Discovered by Kristi Fristi on Discord.

**Comment by Talia-12** [comment]
fixed in the transition to Arithmetics.
