### ISSUE TITLE
Fisherman's Gambit 1 and 2 take different arguments

### ISSUE THREAD

**Issue by Petrify** [gamma-delta/HexMod#447]
## Expected Behavior
Fisherman's Gambit should yank the nth element to the top, Fisherman's Gambit II should do the same but copy instead

## Actual Behavior
Fisherman's Gambit takes an index in range [1, stack size], Fisherman's Gambit II takes an index in range [0, stack size - 1]

## Steps to Reproduce the Problem
Draw Numerical Reflection 0 
Draw Fisherman's Gambit 
-> Error: Expected number between 1 and 4

Draw Numerical Reflection 0 
Draw Fisherman's Gambit II
-> No Error

Specifications
Modpack: ATM 8
Mod Verion: 0.10.3
Minecraft Version: 1.19.2

**Comment by Talia-12** [comment]
this was fixed in my last pull request petra

**Comment by BlastYoBoots** [comment]
I'm guessing that fix isn't in the Fabric release yet?  :(
