### ISSUE TITLE
Add a config to disable giving Patchouli book on first world join

### ISSUE THREAD

**Issue by aaronhowser1** [gamma-delta/HexMod#452]
Apologies if I simply couldn't find it, but with `hexcasting-forge-1.19.2-0.10.3` I couldn't find a config to disable giving the patchouli book on first world join, in either common or server configs.

**Comment by sedyh** [comment]
@aaronhowser1, I think I'm found a fast solution.

The issuance of the book is made according to the guide from patchouli docs.
It is issued not by a mod, but through vanilla advancements.

To turn off the book, just open the mod's .jar and delete `/data/hexcasting/advancements/grant_patchi_book.json` file. That's all!

**Comment by aaronhowser1** [comment]
You can't share modified jars in modpacks, but I can just replace that file using a datapack. Thanks!

**Comment by SamsTheNerd** [comment]
for anyone seeing this in the future there's also an existing datapack https://github.com/SamsTheNerd/hexaddons/tree/main/datapacks/#no-hexbook.

(closing since there are existing solutions and I don't think having it be specifically config is the highest priority)
