### ISSUE TITLE
Some great spells don't give Blind Diversion advancement

### ISSUE THREAD

**Issue by GameGuruGreenGryphon** [gamma-delta/HexMod#46]
### Versions
Minecraft: 1.18.2
Hex: Commit [6568168](https://github.com/gamma-delta/HexMod/commit/6568168854dea4f9da73f15904005feacbcd0f93)
Paucal: Commit [1f1dd45](https://github.com/gamma-delta/PAUCAL/commit/1f1dd45462acbdf1ac1f866e5bcee140bb8847c8)
Forge: 40.0.24

### Issue
Green Sun's Zenith, Red Sun's Zenith, Black Sun's Zenith, Blue Sun's Zenith, White Sun's Zenith, Summon Greater Sentinel, and Flay Mind **do not** give the Blind Diversion advancement when casted successfully.

Create Lava, Summon Rain, Dispel Rain, Summon Lightning, Flight, and Greater Teleport give the Blind Diversion advancement when casted successfully.

**Comment by gamma-delta** [comment]
Good catch!
