### ISSUE TITLE
Break Block spell on amethyst clusters drop no amethyst shards

### ISSUE THREAD

**Issue by GameGuruGreenGryphon** [gamma-delta/HexMod#49]
### Versions
Minecraft: 1.18.2
Forge: 40.0.34
Hex: Commit [767dd99](https://github.com/gamma-delta/HexMod/commit/767dd9983d14088ce6732cab62380b6788770c10)
Paucal: Commit [8f64bef](https://github.com/gamma-delta/PAUCAL/commit/8f64bef48e7a6fe3487c9f460fc3037b1b72803f)
### Issue
Using Break Block on a fully-grown amethyst cluster (which normally drop 2 shards because of the mixin Hex uses) drops 0 shards.
This is because, in vanilla Minecraft, breaking amethyst clusters with pickaxes normally drops 4 shards, and anything else makes it drop 2 shards.
This is an issue because oh my god mining clusters is so tedious and you shouldn't have to do it in the mod that encourages automating tedious personal tasks
This would also be a double issue if [break block inherited enchantments.](https://github.com/gamma-delta/HexMod/issues/47)

I'm guessing that Break Block doesn't count as a pickaxe to amethyst clusters, and that when clusters do the check, they take however many shards it's supposed to drop minus 2.

**Comment by yrsegal** [comment]
Should be fixed now.
