### ISSUE TITLE
Polish Spellbook

### ISSUE THREAD

**Issue by GameGuruGreenGryphon** [gamma-delta/HexMod#5]
### Issues right now:
Sneaking and scrolling while holding the spellbook in your main hand does not work.
You can scroll through your spellbook infinitely, rather than not letting you scroll past an unedited page, allowing you to lose your place in the book.
If this is to be used as a library of foci, you have to remember each foci's position relative to eachother, which is a pain for more and more foci in the spellbook.
Spellbook's tooltip does not allow renaming foci, and if it could, the tooltip always reads "hex.spellbook.tooltip.page" when selecting it.
You have to hover over the spellbook with your cursor to read the contents of said page.
### What I propose
Fix sneak-scrolling, tooltip, and being able to scroll infinitely.
The spellbook should be able to be right-clicked to open to see the contents of it. Foci should be able to be renamed, sorted, and grouped, and said groups being able to be renamed and sorted (and maybe grouped lol)
Add spells to shift what focus is selected in the spellbook for awesome daisy-chains of spells. This also has the consequence of reaching The End and getting chorus fruit for the crafting recipe actually a worthwhile upgrade.

**Comment by yrsegal** [comment]
is this fixed with the introduction of names per page?

**Comment by GameGuruGreenGryphon** [comment]
Moving spells around in the spellbook is still a pain and you cannot select the pages of the book with spells yet, but it's improved a lot.
It still also has the issue that you cannot see the entire contents of the book at once, you have to scroll through every spell which discourages big books.

**Comment by gamma-delta** [comment]
I think the combination of all of wire's polish changes + akashic records makes this closed? at the least, I haven't seen anyone else raise concerns over it.
