### ISSUE TITLE
[FEATURE] Gemini's Gambit 2

### ISSUE THREAD

**Issue by GameGuruGreenGryphon** [gamma-delta/HexMod#50]
### Proposal
Gemini's Gambit 2 is a new stack manipulation pattern that takes an integer and any iota then returns that many copies of an iota.
### But why?
This pattern would be extremely useful to utilize in combination with Thoth's Gambit to create functions that take a variable input.
This would also synergize well with the new abacus item added in 0.7.0.
### Examples
Imagine you want a tree chopping spell. 

In the current version, you have to use a focus in your offhand or hard-code a list size inside the spell. This is because thoth's requires two lists to execute, and is currently the only iterating spell.
If you want your Hex to work by pointing at the bottom of the tree and apply a list of offset vectors to break along, how do you get that list? You either hard-code it, or you use Scribe's Reflection and use some other trinkets to affect the focus containing the dummy list.

With this new pattern, you can work out the list size dynamically using the power of math, if need be.
In the tree chopping case, you can run a function that outputs a list of offset vectors given a number input.
There are many math and logistical patterns that can be used to determine how many times a function can be executed, saving you the offhand slot. 
Being able to load a number from the abacus is also powerful and fun, too.

**Comment by gamma-delta** [comment]
The code is in there rn but there's no pattern to actuate it. It'll be in 0.8.0 ... i'll close this when I impl it

**Comment by gamma-delta** [comment]
Coming in 0.8!
