### ISSUE TITLE
Thoth's and Hermes' doesn't cost media

### ISSUE THREAD

**Issue by GameGuruGreenGryphon** [gamma-delta/HexMod#52]
### Versions
Minecraft: 1.18.2
Forge: 40.0.34
Hex: Commit [767dd99](https://github.com/gamma-delta/HexMod/commit/767dd9983d14088ce6732cab62380b6788770c10)
Paucal: Commit [e90c6e8](https://github.com/gamma-delta/PAUCAL/commit/e90c6e86712ba8782bc3e476343c38933c365fe9)

**Comment by gamma-delta** [comment]
@yrsegal I believe we fixed or did something about this at some point?

**Comment by yrsegal** [comment]
we did, this has been made intentional
