### ISSUE TITLE
Explosion spell doesn't deal damage to yourself

### ISSUE THREAD

**Issue by GameGuruGreenGryphon** [gamma-delta/HexMod#59]
Versions
Minecraft 1.18.2
Forge: 40.0.42
Hex: Commit [620b751](https://github.com/gamma-delta/HexMod/commit/620b7510020b2d387deefb51c72453d714fbe6ad)
Paucal: Commit [92990a8](https://github.com/gamma-delta/PAUCAL/commit/92990a8f19baa918de6a0b53f4f9d631a13b1905)

Casting the spell via impetus also does not deal damage to yourself if you were the one responsible for the activation.
Haven't tested with other players, or in multiplayer.

**Comment by yrsegal** [comment]
psi works the same way, actually. i'm gonna defer to petra on the intentionality or otherwise of this.
