### ISSUE TITLE
Conjure Block doesn't cause a redstone update

### ISSUE THREAD

**Issue by GameGuruGreenGryphon** [gamma-delta/HexMod#60]
### Versions
Minecraft: 1.18.2
Forge: 40.0.34
Hex: Commit [fd20628](https://github.com/gamma-delta/HexMod/commit/fd206287f685261aa257957f6a4eb634db46630f)
Paucal: Commit [92990a8](https://github.com/gamma-delta/PAUCAL/commit/92990a8f19baa918de6a0b53f4f9d631a13b1905)
### Issue
![image](https://user-images.githubusercontent.com/87587913/162596114-93454bb0-ec35-400b-a095-9e0f368a9847.png)
Conjure Block, conjured directly above the redstone torch, does not trigger the Cleric Impetus.
Conjure Block triggers block updates, though, so this works with an Observer's output facing the Cleric Impetus.

**Comment by yrsegal** [comment]
conjured blocks aren't solid. they don't carry a redstone signal

**Comment by GameGuruGreenGryphon** [comment]
![image](https://user-images.githubusercontent.com/87587913/162596404-b2de264f-0069-47eb-aa70-58feac9f43b9.png)
This is the main branch I'm playing on, did you change this?

**Comment by yrsegal** [comment]
I think that's an oversight. nonsolid blocks should not carry redstone signals.

**Comment by GameGuruGreenGryphon** [comment]
![image](https://user-images.githubusercontent.com/87587913/162596480-a4329964-a267-4cee-9b0c-6e2dd864abe5.png)
Looks solid to me.
They're not transparent, either, which disallows redstone currents to overlap.
You can't open chests beneath conjured blocks, they can carry redstone signals, but mobs don't spawn on top of them.

**Comment by yrsegal** [comment]
I think that them acting like glass in that sense is how it should be.
