### ISSUE TITLE
can't make hexcasting items

### ISSUE THREAD

**Issue by kristifristi** [gamma-delta/HexMod#64]
I put the stack of amethyst shards on the ground in the spell stack, I use introspection and retrospection to make a spell list and I draw the symbol to make the cypher/trinket/artifact. The spell sound occurs, the stack clears and the particle effect happens, but both the hexcaster and the amethysts on the ground don't change a bit. I was using version 0.8.0

**Comment by yrsegal** [comment]
known issue, will be fixed with 0.8.1
