### ISSUE TITLE
(0.8.2) Pace purification does not work on players

### ISSUE THREAD

**Issue by SilverSlayer547** [gamma-delta/HexMod#65]
Attempting to use Pace Purification on a player will always return (0, 0, 0).
![image](https://user-images.githubusercontent.com/87394570/165499727-b6556591-22b1-4d83-aac4-edd3a51c61f9.png)

Hex used in trinket
![image](https://user-images.githubusercontent.com/87394570/165499910-6ebcd644-4c4a-4577-8f3f-de47b6f0a963.png)

**Comment by SilverSlayer547** [comment]
After messing around with it for a bit longer, it does appear to work _extremely_ infrequently.
![image](https://user-images.githubusercontent.com/87394570/165501376-8d8c2e3c-868d-4e02-8469-1f229a70633c.png)

**Comment by yrsegal** [comment]
I may have fixed this

**Comment by gamma-delta** [comment]
Gonna mark this as closed for now? if it's not just re-open it please
