### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by VallenFrostweaver** [gamma-delta/HexMod#66]
Minecraft: 1.18.2
Forge: 40.1.0
Hex Casting: 0.8.0 or 0.8.2 (tried both)
Patchouli: 67
Kotlin for Forge: 3.3.2-obf

Crash on startup. Crash report here: [https://hastebin.skyra.pw/zizekuriqe.nestedtext](https://hastebin.skyra.pw/zizekuriqe.nestedtext)

Using GDLauncher I get this as well: 
![image](https://user-images.githubusercontent.com/13642054/165555389-c33b575e-1cc3-4dfa-8551-f31078b3021b.png)

**Comment by yrsegal** [comment]
This is very much not Hex's issue. Something's REALLY weird with your instance.

**Comment by VallenFrostweaver** [comment]
While I'm not disputing what you say is true, enabling Hex Casting and Kotlin for Forge is the only thing that causes a crash. I'll see about disabling other mods and see what I can find out.

**Comment by Noobulus** [comment]
Is PAUCAL installed?

**Comment by Noobulus** [comment]
![Screenshot_20220427_113153](https://user-images.githubusercontent.com/20390143/165570014-acd8f32e-e3ca-4699-b5c6-e9eef0a7a665.png)
They're marked as a relation on my end, but if memory serves GDLauncher won't grab dependencies like that.
![Screenshot_20220427_113720](https://user-images.githubusercontent.com/20390143/165571568-62c86fac-7057-47d3-9791-828e22f00dc0.png)
You're right about the CurseForge page not listing it as a requirement, though. That'll be on @gamma-delta to fix.

**Comment by gamma-delta** [comment]
Whoopsy, good catch 😅😅😅

**Comment by gamma-delta** [comment]
Alright, it's on the CF page now. Thanks!
