### ISSUE TITLE
Having levitation active when flight ends seems to do bad things

### ISSUE THREAD

**Issue by Stevebutnottoomanypeoplehaveit** [gamma-delta/HexMod#69]
[crash-2022-05-12_01.00.35-server.txt](https://github.com/gamma-delta/HexMod/files/8671119/crash-2022-05-12_01.00.35-server.txt)
Crashes immediately, and again on opening world

**Comment by yrsegal** [comment]
That is an ooooold prerelease. This issue is already fixed

**Comment by gamma-delta** [comment]
nice
