### ISSUE TITLE
Multiple Overcast Damage Events in a Single Spell Do Not Stack 

### ISSUE THREAD

**Issue by KirinDave** [gamma-delta/HexMod#77]
I discovered that if you take a spell like `self sqrt(19) impulse` and thoth it many times, you only pay the cost once. I believe that what's happening here is minecraft damage mechanics (aka iframes) are eating the extra damage events. 

This is particularly noticeable with spells that accumulate a large list of coordinates or entities to act on (e.g., mass block breaking spells, or mass entity impulse spells). These are actually better to overcast.

The simple fix is to make it so we pay the sum total of all overcasts for the spell, and if that kills us, so be it. :)

For fixing it while preserving the overcasting design space, I recommend the following:

1. Formally set the maximum overcast cost for any single effect at 20. We should simply die if we pass that.
2. Allow multiple <20 costs to exist in a spell, but as above, make us pay for it.
3. Watch us try not to die as we play with this, cackling.
4. Watch spells get more complex as we build in "safety mechanisms" to make overcasted spells less likely to kill you.

**Comment by yrsegal** [comment]
solved I think
