### ISSUE TITLE
Loud and rude error about a forge-only thing in a loot table

### ISSUE THREAD

**Issue by gamma-delta** [gamma-delta/HexMod#80]
My guess is it's amethyst leaves with a forge-only predicate. To be looked at.

**Comment by yrsegal** [comment]
yeah it's with a forge only predicate. but like. bleh. i don't know how we want to fix this

**Comment by gamma-delta** [comment]
I fixed this a while ago with a bit of a hack but ehh i think it works? i'm messing with datagen rn i'll see if i did actually fix it
