### ISSUE TITLE
Floating-point weirdness with vectors

### ISSUE THREAD

**Issue by shBLOCK** [gamma-delta/HexMod#81]
Multiplying a vector with a negative number causes its 0 elements to turn to -0:
![javaw_Y8r6sFuofI](https://user-images.githubusercontent.com/50770712/169437697-915eaf8e-6729-450c-901b-7eb126dddd86.png)
Comparing (0,0,0)==(-0,-0,-0) works fine (returns 1)
But it doesn't seem to be working well with the Set operations, it thinks (0,0,0) != (-0,-0,-0): (here the XOR operation should think they're the same and return an empty list)
![javaw_yzLLesTmkC](https://user-images.githubusercontent.com/50770712/169438559-299d6d1f-6b75-4e0b-8c14-47dea98ae031.png)
This causes my spell to only work in +x,+y and +z axis.

**Comment by gamma-delta** [comment]
Ah yep that's an easy fix, which I will do tomorrow.

**Comment by gamma-delta** [comment]
just kidding it will be fixed in this next push
![image](https://user-images.githubusercontent.com/29877714/169449569-7f3e3792-ccda-45bb-9543-30123374995c.png)

**Comment by gamma-delta** [comment]
I also fixed the other set operations

**Comment by shBLOCK** [comment]
Thanks!
I absolutely love this mod, it's one of the few mods that is both creative and useful.
Looking forward for the next version!
