### ISSUE TITLE
[FEATURE] Add %(modular) math operation

### ISSUE THREAD

**Issue by shBLOCK** [gamma-delta/HexMod#82]
The modular operation would be very useful on things like generating vectors in an area, while it's possible to simulate it with devide and flooring and stuff, it's still quite annoying.
Also I'm willing to implement it myself and make a PR if that is allowed.

**Comment by gamma-delta** [comment]
Ooh if you could PR it that would be great eeee

Can you make a modulus and euler remainder action with patterns like multiply and divide, but with the stroke "reflecting" off the cross point instead of going through?

**Comment by shBLOCK** [comment]
Okay, I'll start to work on that

**Comment by shBLOCK** [comment]
The progress is going smooth so far, but I'm not sure what the euler remainder operation is, though my search online is looks like it's an operation that takes three inputs? I'm not sure if that's what you mint or not.
(Btw I'm not an native English speaker, so you may find my English a bit weird, I'm sorry about that)
Also I'm not a good namer, so I'd like to ask about the localization name of the operators.

**Comment by shBLOCK** [comment]
![java_Ggk4MEeAgM](https://user-images.githubusercontent.com/50770712/169674035-57f9a2ab-9ef1-48b3-bf2f-8316ffe4fe76.png)
Modular operation seems to be working 😄
