### ISSUE TITLE
Conjured blocks are missing model files.

### ISSUE THREAD

**Issue by AmyMialee** [gamma-delta/HexMod#94]
This means the held item and landing particles are missing textures.

**Comment by yrsegal** [comment]
There shouldn't *be* a held item form.

**Comment by gamma-delta** [comment]
Yes there should because that way we can have patchi shift-right-click hop to the correct page and also ctrl+pick block is handy for building in creative mode

**Comment by AmyMialee** [comment]
Yea it's for nbt pick blocking, which is insanely handy.
