### ISSUE TITLE
Bug - Flight Spell not working

### ISSUE THREAD

**Issue by Kurotsune77** [gamma-delta/HexMod#99]
When I try to cast Flight Spell
![2022-06-05_19 08 31](https://user-images.githubusercontent.com/96918301/172062027-4083308b-0a04-4e44-9500-cd8e2bcf0eda.png)

it just consumes my media (I used charged crystals in this example for simplicity), makes some particles at my position, seemingly changes my FOV for a split second and does nothing in the finale

First noticed it in a modpack and then tried it with only Hex Casting and dependencies, with the same result

**Comment by yrsegal** [comment]
Will be fixed in 0.9.
